! This subroutine is generated by the automaic differentiation tool Tapenade
! Input variables
!  It calculate the derivatives with respect to shock acceleration term shockac
!  
!  In every points at (i,Ny,k)
!  This subroutine gives:
!  shockhb       = d ShockAc / d shockH       * shockAc 
!  shockhdxib    = d ShockAc / d shockHdxi    * shockAc
!  shockhdzetab  = d ShockAc / d shockHdzeta  * shockAc
!  shockvb       = d ShockAc / d shockV       * shockAc
!  shockvdxib    = d ShockAc / d shockVdxi    * shockAc
!  shockvdzetab  = d ShockAc / d shockVdzeta  * shockAc
! Other input variables are only used as parameters
SUBROUTINE CALCULATESHOCKAC_B(shockh, shockhb, shockhdxi, shockhdxib, &
& shockhdzeta, shockhdzetab, shockv, shockvb, shockvdxi, shockvdxib, &
& shockvdzeta, shockvdzetab, shockac, shockacb, wallsxdxi, wallsydxi, &
& wallszdxi, wallsxdzeta, wallsydzeta, wallszdzeta, wallnormalx, &
& wallnormaly, wallnormalz, wallnormalxdxi, wallnormalydxi, &
& wallnormalzdxi, wallnormalxdzeta, wallnormalydzeta, wallnormalzdzeta, &
& heta, hetadxi, hetadeta, hetadzeta, cv_inf, finv_inf, ginv_inf, &
& hinv_inf, ducons0, u_inf, v_inf, w_inf, p_inf, rho_inf, gamma, &
& mach_ref)
  USE SF_Constant, ONLY: ik,rk
  IMPLICIT NONE
  INTEGER, PARAMETER :: numvar=5
! Input variables
  REAL(kind = rk), INTENT(IN) :: shockh, shockhdxi, shockhdzeta, shockv, &
& shockvdxi, shockvdzeta
  REAL(kind = rk) :: shockhb, shockhdxib, shockhdzetab, shockvb, shockvdxib, &
& shockvdzetab
! Output variables
  REAL(kind = rk) :: shockac
  REAL(kind = rk) :: shockacb
! Input unchanged variables with respect to the geometry
  REAL(kind = rk), INTENT(IN) :: wallsxdxi, wallsydxi, wallszdxi, wallsxdzeta, &
& wallsydzeta, wallszdzeta
  REAL(kind = rk), INTENT(IN) :: wallnormalx, wallnormaly, wallnormalz
  REAL(kind = rk), INTENT(IN) :: wallnormalxdxi, wallnormalydxi, wallnormalzdxi
  REAL(kind = rk), INTENT(IN) :: wallnormalxdzeta, wallnormalydzeta, &
& wallnormalzdzeta
  REAL(kind = rk), INTENT(IN) :: heta, hetadxi, hetadeta, hetadzeta
! Flow related variables
  REAL(kind = rk), INTENT(IN) :: u_inf, v_inf, w_inf, p_inf, rho_inf, gamma, &
& mach_ref
  REAL(kind = rk), INTENT(IN) :: cv_inf(5), finv_inf(5), ginv_inf(5), hinv_inf(5)&
& , ducons0(5)
! Local variables
  REAL(kind = rk) :: xdxi, xdeta, xdzeta
  REAL(kind = rk) :: xdxib, xdetab, xdzetab
  REAL(kind = rk) :: ydxi, ydeta, ydzeta
  REAL(kind = rk) :: ydxib, ydetab, ydzetab
  REAL(kind = rk) :: zdxi, zdeta, zdzeta
  REAL(kind = rk) :: zdxib, zdetab, zdzetab
  !REAL(kind = rk) :: xxitau, xetatau, xzetatau
  !REAL(kind = rk) :: yxitau, yetatau, yzetatau
  !REAL(kind = rk) :: zxitau, zetatau, zzetatau
  REAL(kind = rk) :: temp, jaco !, invjacodt
  REAL(kind = rk) :: tempb, jacob
  !REAL(kind = rk) :: xix, xiy, xiz
  REAL(kind = rk) :: etax, etay, etaz
  !REAL(kind = rk) :: zetax, zetay, zetaz
  REAL(kind = rk) :: etaxb, etayb, etazb
  !REAL(kind = rk) :: nablaxi
  REAL(kind = rk) :: nablaeta
  !REAL(kind = rk) :: nablazeta
  REAL(kind = rk) :: nablaetab
  REAL(kind = rk) :: shocknormalx, shocknormaly, shocknormalz
  REAL(kind = rk) :: shocknormalxb, shocknormalyb, shocknormalzb
  REAL(kind = rk) :: shockxtau, shockytau, shockztau
  REAL(kind = rk) :: shockxtaub, shockytaub, shockztaub
  REAL(kind = rk) :: shockxtaudxi, shockytaudxi, shockztaudxi
  REAL(kind = rk) :: shockxtaudxib, shockytaudxib, shockztaudxib
  REAL(kind = rk) :: shockxtaudzeta, shockytaudzeta, shockztaudzeta
  REAL(kind = rk) :: shockxtaudzetab, shockytaudzetab, shockztaudzetab
  REAL(kind = rk) :: tempax, tempay, tempaz
  REAL(kind = rk) :: tempaxb, tempayb, tempazb
  REAL(kind = rk) :: detadt, shockvn, ax_tau, ay_tau, az_tau
  REAL(kind = rk) :: detadtb, shockvnb, ax_taub, ay_taub, az_taub
  REAL(kind = rk) :: delta_inf, masn2inf, deltashkuinf, u_ijk, v_ijk, w_ijk, &
& p_ijk, rho_ijk, c_ijk!, t_ijk
  REAL(kind = rk) :: delta_infb, masn2infb, deltashkuinfb, u_ijkb, v_ijkb, w_ijkb&
& , p_ijkb, rho_ijkb, c_ijkb
  REAL(kind = rk) :: locuns
  REAL(kind = rk) :: locunsb
  REAL(kind = rk) :: lam5, l5(5), sum_l5_u, sum_l5_fg, fg
  REAL(kind = rk) :: lam5b, l5b(5), sum_l5_ub, sum_l5_fgb, fgb
  INTEGER :: ivar
  REAL(kind = rk) :: u0_ijk(5), invf_ijk(5), invg_ijk(5), invh_ijk(5)
  REAL(kind = rk) :: u0_ijkb(5), invf_ijkb(5), invg_ijkb(5), invh_ijkb(5)
  INTRINSIC SQRT
  REAL(kind = rk) :: tempb0
  REAL(kind = rk) :: temp0
  REAL(kind = rk) :: tempb1
  REAL(kind = rk) :: temp1
  REAL(kind = rk) :: tempb2
! In the following parts, we need to recalculate the geometry variables
! 
  xdxi = wallsxdxi + (wallnormalxdxi*shockh+wallnormalx*shockhdxi)*heta &
&   + wallnormalx*shockh*hetadxi
  ydxi = wallsydxi + (wallnormalydxi*shockh+wallnormaly*shockhdxi)*heta &
&   + wallnormaly*shockh*hetadxi
  zdxi = wallszdxi + (wallnormalzdxi*shockh+wallnormalz*shockhdxi)*heta &
&   + wallnormalz*shockh*hetadxi
  xdeta = wallnormalx*shockh*hetadeta
  ydeta = wallnormaly*shockh*hetadeta
  zdeta = wallnormalz*shockh*hetadeta
  xdzeta = wallsxdzeta + (wallnormalxdzeta*shockh+wallnormalx*&
&   shockhdzeta)*heta + wallnormalx*shockh*hetadzeta
  ydzeta = wallsydzeta + (wallnormalydzeta*shockh+wallnormaly*&
&   shockhdzeta)*heta + wallnormaly*shockh*hetadzeta
  zdzeta = wallszdzeta + (wallnormalzdzeta*shockh+wallnormalz*&
&   shockhdzeta)*heta + wallnormalz*shockh*hetadzeta
  temp = xdxi*(ydeta*zdzeta-zdeta*ydzeta) + xdeta*(ydzeta*zdxi-ydxi*&
&   zdzeta) + xdzeta*(ydxi*zdeta-ydeta*zdxi)
  jaco = 1.d0/temp
  etax = -(jaco*(ydxi*zdzeta-zdxi*ydzeta))
  etay = jaco*(xdxi*zdzeta-zdxi*xdzeta)
  etaz = -(jaco*(xdxi*ydzeta-ydxi*xdzeta))
  nablaeta = SQRT(etax*etax + etay*etay + etaz*etaz)
  shocknormalx = etax/nablaeta
  shocknormaly = etay/nablaeta
  shocknormalz = etaz/nablaeta
  shockxtau = wallnormalx*shockv
  shockytau = wallnormaly*shockv
  shockztau = wallnormalz*shockv
  shockxtaudxi = wallnormalxdxi*shockv + wallnormalx*shockvdxi
  shockytaudxi = wallnormalydxi*shockv + wallnormaly*shockvdxi
  shockztaudxi = wallnormalz*shockvdxi
  shockxtaudzeta = wallnormalx*shockvdzeta
  shockytaudzeta = wallnormaly*shockvdzeta
  shockztaudzeta = wallnormalz*shockvdzeta
  tempax = shockytaudzeta*zdxi + shockztaudxi*ydzeta - shockytaudxi*&
&   zdzeta - shockztaudzeta*ydxi
  tempay = shockxtaudxi*zdzeta + shockztaudzeta*xdxi - shockxtaudzeta*&
&   zdxi - shockztaudxi*xdzeta
  tempaz = shockxtaudzeta*ydxi + shockytaudxi*xdzeta - shockxtaudxi*&
&   ydzeta - shockytaudzeta*xdxi
  detadt = -(etax*shockxtau+etay*shockytau+etaz*shockztau)
  shockvn = -(detadt/nablaeta)
  ax_tau = jaco*tempax/nablaeta
  ay_tau = jaco*tempay/nablaeta
  az_tau = jaco*tempaz/nablaeta
! Obtain the variables behind the shock
! Velocity ahead of the shocks with respect to the moving shock normal
  delta_inf = u_inf*shocknormalx + v_inf*shocknormaly + w_inf*&
&   shocknormalz - shockv*(wallnormalx*shocknormalx+wallnormaly*&
&   shocknormaly+wallnormalz*shocknormalz)
! Shock normal Mach number^2
  masn2inf = (mach_ref*delta_inf)**2.d0
! Velocity normal to the shock after the shock
  deltashkuinf = 2.d0*delta_inf/(gamma+1.d0)*(1.d0/masn2inf-1.d0)
  u_ijk = u_inf + deltashkuinf*shocknormalx
  v_ijk = v_inf + deltashkuinf*shocknormaly
  w_ijk = w_inf + deltashkuinf*shocknormalz
  p_ijk = p_inf*(1.d0+2.d0*gamma/(gamma+1.d0)*(masn2inf-1.d0))
  rho_ijk = rho_inf*(gamma+1.d0)*masn2inf/((gamma-1.d0)*masn2inf+2.d0)
  c_ijk = SQRT(gamma*p_ijk/rho_ijk)
! Update the fluxes and new conservative variables
! invF_IJK(5),invG_IJK(5),invH_IJK(5),U0_IJK(5)
! Update the fluxes and new conservative variables
! invF_IJK(5),invG_IJK(5),invH_IJK(5),U0_IJK(5)
!  CALL UtoCV_CPG(Rho_IJK,U_IJK,V_IJK,W_IJK,P_IJK,U0_IJK)
  u0_ijk(1) = rho_ijk
  u0_ijk(2) = rho_ijk*u_ijk
  u0_ijk(3) = rho_ijk*v_ijk
  u0_ijk(4) = rho_ijk*w_ijk
  u0_ijk(5) = p_ijk/(gamma-1.d0) + 0.5d0*rho_ijk*(u_ijk*u_ijk+v_ijk*&
&   v_ijk+w_ijk*w_ijk)
!  CALL UtoFlux_CPG3D(Rho_IJK,U_IJK,V_IJK,W_IJK,P_IJK,invF_IJK,invG_IJK,invH_IJK)
  invf_ijk(1) = rho_ijk*u_ijk
  invf_ijk(2) = rho_ijk*u_ijk*u_ijk + p_ijk
  invf_ijk(3) = rho_ijk*u_ijk*v_ijk
  invf_ijk(4) = rho_ijk*u_ijk*w_ijk
  invf_ijk(5) = (p_ijk/(gamma-1.d0)+0.5d0*rho_ijk*(u_ijk*u_ijk+v_ijk*&
&   v_ijk+w_ijk*w_ijk)+p_ijk)*u_ijk
  invg_ijk(1) = rho_ijk*v_ijk
  invg_ijk(2) = rho_ijk*v_ijk*u_ijk
  invg_ijk(3) = rho_ijk*v_ijk*v_ijk + p_ijk
  invg_ijk(4) = rho_ijk*v_ijk*w_ijk
  invg_ijk(5) = (p_ijk/(gamma-1.d0)+0.5d0*rho_ijk*(u_ijk*u_ijk+v_ijk*&
&   v_ijk+w_ijk*w_ijk)+p_ijk)*v_ijk
  invh_ijk(1) = rho_ijk*w_ijk
  invh_ijk(2) = rho_ijk*w_ijk*u_ijk
  invh_ijk(3) = rho_ijk*w_ijk*v_ijk
  invh_ijk(4) = rho_ijk*w_ijk*w_ijk + p_ijk
  invh_ijk(5) = (p_ijk/(gamma-1.d0)+0.5d0*rho_ijk*(u_ijk*u_ijk+v_ijk*&
&   v_ijk+w_ijk*w_ijk)+p_ijk)*w_ijk
! Calculate the shock accelerations
! Calculate the local normal
  locuns = u_ijk*shocknormalx + v_ijk*shocknormaly + w_ijk*shocknormalz
  lam5 = locuns - shockvn + c_ijk
  l5(1) = 0.5d0*(gamma-1.d0)*(u_ijk*u_ijk+v_ijk*v_ijk+w_ijk*w_ijk) - &
&   locuns*c_ijk
  l5(2) = -((gamma-1.d0)*u_ijk) + shocknormalx*c_ijk
  l5(3) = -((gamma-1.d0)*v_ijk) + shocknormaly*c_ijk
  l5(4) = -((gamma-1.d0)*w_ijk) + shocknormalz*c_ijk
  l5(5) = gamma - 1.d0
  sum_l5_u = 0.d0
  sum_l5_fg = 0.d0
  DO ivar=1,numvar
    !CALL PUSHREAL8(fg)
    fg = lam5*ducons0(ivar) + ax_tau*(invf_ijk(ivar)-finv_inf(ivar)) + &
&     ay_tau*(invg_ijk(ivar)-ginv_inf(ivar)) + az_tau*(invh_ijk(ivar)-&
&     hinv_inf(ivar))
    sum_l5_u = sum_l5_u + l5(ivar)*(u0_ijk(ivar)-cv_inf(ivar))
    sum_l5_fg = sum_l5_fg + l5(ivar)*fg
  END DO
! Calculate the ShockAc
  shockac = sum_l5_fg/sum_l5_u - (ax_tau*shockxtau+ay_tau*shockytau+&
&   az_tau*shockztau)
  temp1 = wallnormalx*shocknormalx + wallnormaly*shocknormaly + &
&   wallnormalz*shocknormalz
  tempb2 = -(shockac*shockacb/temp1**2)
  shockacb = shockacb/temp1
  shocknormalxb = wallnormalx*tempb2
  shocknormalyb = wallnormaly*tempb2
  shocknormalzb = wallnormalz*tempb2
  sum_l5_fgb = shockacb/sum_l5_u
  sum_l5_ub = -(sum_l5_fg*shockacb/sum_l5_u**2)
  ax_taub = -(shockxtau*shockacb)
  shockxtaub = -(ax_tau*shockacb)
  ay_taub = -(shockytau*shockacb)
  shockytaub = -(ay_tau*shockacb)
  az_taub = -(shockztau*shockacb)
  shockztaub = -(az_tau*shockacb)
  l5b = 0.0_8
  u0_ijkb = 0.0_8
  invf_ijkb = 0.0_8
  invg_ijkb = 0.0_8
  lam5b = 0.0_8
  invh_ijkb = 0.0_8
  DO ivar=numvar,1,-1
    l5b(ivar) = l5b(ivar) + fg*sum_l5_fgb + (u0_ijk(ivar)-cv_inf(ivar))*&
&     sum_l5_ub
    fgb = l5(ivar)*sum_l5_fgb
    u0_ijkb(ivar) = u0_ijkb(ivar) + l5(ivar)*sum_l5_ub
    !CALL POPREAL8(fg)
    lam5b = lam5b + ducons0(ivar)*fgb
    ax_taub = ax_taub + (invf_ijk(ivar)-finv_inf(ivar))*fgb
    invf_ijkb(ivar) = invf_ijkb(ivar) + ax_tau*fgb
    ay_taub = ay_taub + (invg_ijk(ivar)-ginv_inf(ivar))*fgb
    invg_ijkb(ivar) = invg_ijkb(ivar) + ay_tau*fgb
    az_taub = az_taub + (invh_ijk(ivar)-hinv_inf(ivar))*fgb
    invh_ijkb(ivar) = invh_ijkb(ivar) + az_tau*fgb
  END DO
  tempb2 = (gamma-1.d0)*0.5d0*l5b(1)
  c_ijkb = shocknormalz*l5b(4) + shocknormaly*l5b(3) + shocknormalx*l5b(&
&   2) + lam5b - locuns*l5b(1)
  w_ijkb = 2*w_ijk*tempb2 - (gamma-1.d0)*l5b(4)
  v_ijkb = 2*v_ijk*tempb2 - (gamma-1.d0)*l5b(3)
  u_ijkb = 2*u_ijk*tempb2 - (gamma-1.d0)*l5b(2)
  locunsb = lam5b - c_ijk*l5b(1)
  temp0 = u_ijk*u_ijk + v_ijk*v_ijk + w_ijk*w_ijk
  tempb2 = w_ijk*invh_ijkb(5)
  p_ijkb = (1.0/(gamma-1.d0)+1.0)*tempb2
  rho_ijkb = temp0*0.5d0*tempb2
  tempb1 = rho_ijk*0.5d0*tempb2
  u_ijkb = u_ijkb + shocknormalx*locunsb + 2*u_ijk*tempb1
  v_ijkb = v_ijkb + shocknormaly*locunsb + 2*v_ijk*tempb1
  w_ijkb = w_ijkb + shocknormalz*locunsb + (p_ijk/(gamma-1.d0)+0.5d0*(&
&   rho_ijk*temp0)+p_ijk)*invh_ijkb(5) + 2*w_ijk*tempb1
  temp0 = u_ijk*u_ijk + v_ijk*v_ijk + w_ijk*w_ijk
  tempb2 = v_ijk*invg_ijkb(5)
  rho_ijkb = rho_ijkb + w_ijk**2*invh_ijkb(4) + w_ijk*v_ijk*invh_ijkb(3)&
&   + w_ijk*u_ijk*invh_ijkb(2) + w_ijk*invh_ijkb(1) + temp0*0.5d0*tempb2
  p_ijkb = p_ijkb + invh_ijkb(4) + (1.0/(gamma-1.d0)+1.0)*tempb2
  tempb1 = rho_ijk*0.5d0*tempb2
  w_ijkb = w_ijkb + 2*w_ijk*rho_ijk*invh_ijkb(4) + rho_ijk*v_ijk*&
&   invh_ijkb(3) + rho_ijk*u_ijk*invh_ijkb(2) + rho_ijk*invh_ijkb(1) + 2&
&   *w_ijk*tempb1
  v_ijkb = v_ijkb + rho_ijk*w_ijk*invh_ijkb(3) + (p_ijk/(gamma-1.d0)+&
&   0.5d0*(rho_ijk*temp0)+p_ijk)*invg_ijkb(5) + 2*v_ijk*tempb1
  u_ijkb = u_ijkb + rho_ijk*w_ijk*invh_ijkb(2) + 2*u_ijk*tempb1
  temp0 = u_ijk*u_ijk + v_ijk*v_ijk + w_ijk*w_ijk
  tempb2 = u_ijk*invf_ijkb(5)
  rho_ijkb = rho_ijkb + v_ijk*w_ijk*invg_ijkb(4) + v_ijk**2*invg_ijkb(3)&
&   + v_ijk*u_ijk*invg_ijkb(2) + v_ijk*invg_ijkb(1) + temp0*0.5d0*tempb2
  p_ijkb = p_ijkb + invg_ijkb(3) + (1.0/(gamma-1.d0)+1.0)*tempb2
  tempb1 = rho_ijk*0.5d0*tempb2
  tempb2 = rho_ijk*0.5d0*u0_ijkb(5)
  v_ijkb = v_ijkb + rho_ijk*w_ijk*invg_ijkb(4) + 2*v_ijk*rho_ijk*&
&   invg_ijkb(3) + rho_ijk*u_ijk*invg_ijkb(2) + rho_ijk*invg_ijkb(1) + 2&
&   *v_ijk*tempb1 + rho_ijk*u_ijk*invf_ijkb(3) + 2*v_ijk*tempb2 + &
&   rho_ijk*u0_ijkb(3)
  w_ijkb = w_ijkb + rho_ijk*v_ijk*invg_ijkb(4) + 2*w_ijk*tempb1 + &
&   rho_ijk*u_ijk*invf_ijkb(4) + 2*w_ijk*tempb2 + rho_ijk*u0_ijkb(4)
  u_ijkb = u_ijkb + rho_ijk*v_ijk*invg_ijkb(2) + (p_ijk/(gamma-1.d0)+&
&   0.5d0*(rho_ijk*temp0)+p_ijk)*invf_ijkb(5) + 2*u_ijk*tempb1 + rho_ijk&
&   *w_ijk*invf_ijkb(4) + rho_ijk*v_ijk*invf_ijkb(3) + 2*u_ijk*rho_ijk*&
&   invf_ijkb(2) + rho_ijk*invf_ijkb(1) + 2*u_ijk*tempb2 + rho_ijk*&
&   u0_ijkb(2)

!  IF (gamma*(p_ijk/rho_ijk) .EQ. 0.0) THEN
!    tempb2 = 0.0_8
!  ELSE
    tempb2 = gamma*c_ijkb/(rho_ijk*2.0*SQRT(gamma*(p_ijk/rho_ijk)))
!  END IF

  rho_ijkb = rho_ijkb + u_ijk*w_ijk*invf_ijkb(4) + u_ijk*v_ijk*invf_ijkb&
&   (3) + u_ijk**2*invf_ijkb(2) + u_ijk*invf_ijkb(1) + (u_ijk**2+v_ijk**&
&   2+w_ijk**2)*0.5d0*u0_ijkb(5) + w_ijk*u0_ijkb(4) + v_ijk*u0_ijkb(3) +&
&   u_ijk*u0_ijkb(2) + u0_ijkb(1) - p_ijk*tempb2/rho_ijk
  p_ijkb = p_ijkb + invf_ijkb(2) + u0_ijkb(5)/(gamma-1.d0) + tempb2
  tempb2 = rho_inf*(gamma+1.d0)*rho_ijkb/((gamma-1.d0)*masn2inf+2.d0)
  deltashkuinfb = shocknormalz*w_ijkb + shocknormaly*v_ijkb + &
&   shocknormalx*u_ijkb
  masn2infb = (1.0-(gamma-1.d0)*masn2inf/((gamma-1.d0)*masn2inf+2.d0))*&
&   tempb2 + gamma*2.d0*p_inf*p_ijkb/(gamma+1.d0) - delta_inf*2.d0*&
&   deltashkuinfb/(masn2inf**2*(gamma+1.d0))
  delta_infb = (1.0/masn2inf-1.d0)*2.d0*deltashkuinfb/(gamma+1.d0) + &
&   mach_ref**2*2.d0*delta_inf*masn2infb
  tempb2 = -(shockv*delta_infb)
  l5b(5) = 0.0_8
  shocknormalzb = shocknormalzb + c_ijk*l5b(4) + w_ijk*locunsb + &
&   deltashkuinf*w_ijkb + w_inf*delta_infb + wallnormalz*tempb2
  l5b(4) = 0.0_8
  shocknormalyb = shocknormalyb + c_ijk*l5b(3) + v_ijk*locunsb + &
&   deltashkuinf*v_ijkb + v_inf*delta_infb + wallnormaly*tempb2
  l5b(3) = 0.0_8
  shocknormalxb = shocknormalxb + c_ijk*l5b(2) + u_ijk*locunsb + &
&   deltashkuinf*u_ijkb + u_inf*delta_infb + wallnormalx*tempb2
  l5b(2) = 0.0_8
  shockvnb = -lam5b
  invh_ijkb(5) = 0.0_8
  invh_ijkb(4) = 0.0_8
  invh_ijkb(3) = 0.0_8
  invh_ijkb(2) = 0.0_8
  invg_ijkb(5) = 0.0_8
  invg_ijkb(4) = 0.0_8
  invg_ijkb(3) = 0.0_8
  invg_ijkb(2) = 0.0_8
  invf_ijkb(5) = 0.0_8
  invf_ijkb(4) = 0.0_8
  invf_ijkb(3) = 0.0_8
  invf_ijkb(2) = 0.0_8
  u0_ijkb(5) = 0.0_8
  u0_ijkb(4) = 0.0_8
  u0_ijkb(3) = 0.0_8
  u0_ijkb(2) = 0.0_8
  tempb2 = az_taub/nablaeta
  jacob = tempaz*tempb2
  tempazb = jaco*tempb2
  nablaetab = -(jaco*tempaz*tempb2/nablaeta)
  tempb2 = ay_taub/nablaeta
  jacob = jacob + tempay*tempb2
  tempayb = jaco*tempb2
  nablaetab = nablaetab - jaco*tempay*tempb2/nablaeta
  tempb2 = ax_taub/nablaeta
  jacob = jacob + tempax*tempb2
  tempaxb = jaco*tempb2
  nablaetab = nablaetab + detadt*shockvnb/nablaeta**2 - jaco*tempax*&
&   tempb2/nablaeta - etaz*shocknormalzb/nablaeta**2 - etay*&
&   shocknormalyb/nablaeta**2 - etax*shocknormalxb/nablaeta**2
  detadtb = -(shockvnb/nablaeta)
  shockxtaub = shockxtaub - etax*detadtb
  shockytaub = shockytaub - etay*detadtb
  shockztaub = shockztaub - etaz*detadtb
  shockxtaudzetab = ydxi*tempazb - zdxi*tempayb
  shockytaudxib = xdzeta*tempazb - zdzeta*tempaxb
  shockxtaudxib = zdzeta*tempayb - ydzeta*tempazb
  shockvb = wallnormalydxi*shockytaudxib - (wallnormalx*shocknormalx+&
&   wallnormaly*shocknormaly+wallnormalz*shocknormalz)*delta_infb + &
&   wallnormalxdxi*shockxtaudxib + wallnormalz*shockztaub + wallnormaly*&
&   shockytaub + wallnormalx*shockxtaub
  shockytaudzetab = zdxi*tempaxb - xdxi*tempazb
  shockztaudzetab = xdxi*tempayb - ydxi*tempaxb
  shockztaudxib = ydzeta*tempaxb - xdzeta*tempayb
  shockvdzetab = wallnormalz*shockztaudzetab + wallnormaly*&
&   shockytaudzetab + wallnormalx*shockxtaudzetab
  shockvdxib = wallnormalz*shockztaudxib + wallnormaly*shockytaudxib + &
&   wallnormalx*shockxtaudxib

!  IF (etax**2 + etay**2 + etaz**2 .EQ. 0.0) THEN
!    tempb2 = 0.0_8
!  ELSE
    tempb2 = nablaetab/(2.0*SQRT(etax**2+etay**2+etaz**2))
!  END IF

  etaxb = shocknormalxb/nablaeta - shockxtau*detadtb + 2*etax*tempb2
  etayb = shocknormalyb/nablaeta - shockytau*detadtb + 2*etay*tempb2
  etazb = shocknormalzb/nablaeta - shockztau*detadtb + 2*etaz*tempb2
  jacob = jacob + (xdxi*zdzeta-zdxi*xdzeta)*etayb - (xdxi*ydzeta-ydxi*&
&   xdzeta)*etazb - (ydxi*zdzeta-zdxi*ydzeta)*etaxb
  tempb2 = -(jaco*etazb)
  ydxib = shockxtaudzeta*tempazb - shockztaudzeta*tempaxb - xdzeta*&
&   tempb2
  xdzetab = shockytaudxi*tempazb - shockztaudxi*tempayb - ydxi*tempb2
  ydzetab = shockztaudxi*tempaxb - shockxtaudxi*tempazb + xdxi*tempb2
  xdxib = shockztaudzeta*tempayb - shockytaudzeta*tempazb + ydzeta*&
&   tempb2
  tempb2 = jaco*etayb
  zdzetab = shockxtaudxi*tempayb + xdxi*tempb2 - shockytaudxi*tempaxb
  zdxib = shockytaudzeta*tempaxb - shockxtaudzeta*tempayb - xdzeta*&
&   tempb2
  tempb = -(jacob/temp**2)
  xdxib = xdxib + zdzeta*tempb2 + (ydeta*zdzeta-zdeta*ydzeta)*tempb
  xdzetab = xdzetab + (ydxi*zdeta-ydeta*zdxi)*tempb - zdxi*tempb2
  tempb2 = -(jaco*etaxb)
  ydxib = ydxib + zdzeta*tempb2
  zdxib = zdxib - ydzeta*tempb2
  tempb0 = xdxi*tempb
  xdetab = (ydzeta*zdxi-ydxi*zdzeta)*tempb
  tempb1 = xdeta*tempb
  zdzetab = zdzetab + ydxi*tempb2 + ydeta*tempb0 - ydxi*tempb1
  ydzetab = ydzetab + zdxi*tempb1 - zdxi*tempb2 - zdeta*tempb0
  tempb2 = xdzeta*tempb
  ydxib = ydxib + zdeta*tempb2 - zdzeta*tempb1
  zdetab = ydxi*tempb2 - ydzeta*tempb0
  ydetab = zdzeta*tempb0 - zdxi*tempb2
  zdxib = zdxib + ydzeta*tempb1 - ydeta*tempb2
  shockhb = (wallnormalzdzeta*heta+wallnormalz*hetadzeta)*zdzetab + (&
&   wallnormalydzeta*heta+wallnormaly*hetadzeta)*ydzetab + (&
&   wallnormalxdzeta*heta+wallnormalx*hetadzeta)*xdzetab + wallnormalz*&
&   hetadeta*zdetab + wallnormaly*hetadeta*ydetab + wallnormalx*hetadeta&
&   *xdetab + (wallnormalzdxi*heta+wallnormalz*hetadxi)*zdxib + (&
&   wallnormalydxi*heta+wallnormaly*hetadxi)*ydxib + (wallnormalxdxi*&
&   heta+wallnormalx*hetadxi)*xdxib
  shockhdzetab = wallnormalz*heta*zdzetab + wallnormaly*heta*ydzetab + &
&   wallnormalx*heta*xdzetab
  shockhdxib = wallnormalz*heta*zdxib + wallnormaly*heta*ydxib + &
&   wallnormalx*heta*xdxib
  shockacb = 0.0_8

END SUBROUTINE CALCULATESHOCKAC_B