subroutine Initial_Grid
  use SF_Constant,  only: ik,rk,pi,overLAP
  use SF_CFD_Global,only: Nx,nx_local,Ny,Nz,nz_local,Gamma,&
                          xim,ximax,sigma_y,yim,ymax,R_head,LModel,Nx_head,theta_p_rad,&
                          Mach_Normal,Nx_flate,Nx_head_hf,theta_p_deg
  use MPI_GLOBAL,   only: MyId,I_offset,K_offset,npx,npz
  ! arrays and matrixes
  use SF_CFD_Global,only: Heta,WallSX,WallSY,WallSZ,WallNormalX,WallNormalY,WallNormalZ,Sxi_Surface
  use SF_CFD_Global,only: HetaDeta,HetaDxi,HetaDzeta
  use SF_CFD_Global,only: WallSXdxi,WallSYdxi,WallSZdxi
  use SF_CFD_Global,only: WallSXdzeta,WallSYdzeta,WallSZdzeta
  use SF_CFD_Global,only: WallNormalXdxi,WallNormalYdxi,WallNormalZdxi
  use SF_CFD_Global,only: WallNormalXdzeta,WallNormalYdzeta,WallNormalZdzeta
  use SF_CFD_Global,only: ShockH,ShockV,X_grid,Y_grid,Z_grid,Lz_start,Lz_end
  use SF_CFD_Global,only: Geometry_Type
  ! subroutines
  use MPI_GLOBAL,     only: Parallel_Exchange,Parallel_Exchange_Surface 
  use OutputParaView, only: output_initial_grid
  use FD5_Order,      only: Cal_Deri_SurfDxi_5th_ce,Cal_Deri_Deta_5th_ce,&
                           &Cal_Deri_Dxi_5th_ce,Cal_Deri_Dzeta_5th_ce
    implicit none

    ! Local variables
           logical :: dir_exists
  INTEGER( kind=ik)::ic,jc,kc,ic_global,kc_global
  REAL( kind = rk )::S_head,S_flate,S_total
  REAL( kind = rk )::sxi_nxr
  ! Define some emperical Shock shape variables
  REAL( kind = rk )::delta, Rc, tan2
  ! Cluster coefficients along eta direction
  REAL( kind = rk )::eta_ay,eta_by,Ytemp,eta
  ! Coefficients along xi directions
  REAL( kind = rk )::xi_ax,xi_bx,xi
  REAL( kind = rk )::sxi(1:Nx_head_hf)
  REAL( kind = rk )::sxi_total(1:Nx_head)
  REAL( kind = rk )::theta_lcl
  REAL( kind = rk )::ds1,ds_uni,ds2
  REAL( kind = rk )::xx_flateplate(1:Nx_flate)
  REAL( kind = rk )::beta
  REAL( kind = rk )::GWallSX(1:Nx)
  REAL( kind = rk )::GWallSY(1:Nx)
  REAL( kind = rk )::GWallSZ(1:Nz)
  REAL( kind = rk )::GWallNormalX(1:Nx)
  REAL( kind = rk )::GWallNormalY(1:Nx)
  REAL( kind = rk )::GShockH(1:Nx)
  REAL( kind = rk )::GSxi_Surface(1:Nx)
  REAL( kind = rk )::shk_xgrid2,shk_ygrid2,temp

  ! Here we briefly describe the grid generation method
  ! This solver is used only for the grid in the x-y plane
  ! Then the grid in the z direction is generated by the duplication of the x-y plane
  ! The grid is generated by the following steps

  ! The geometry is defined by two parts, they first part is the rounded head part
  ! The second part is the flat plate part
  ! The grid is generated to have a blunt cone shape

  ! Define the streamwise sxi
  sxi          =  0.0_rk;
  sxi_total    =  0.0_rk;
  
  ! Global Wall Surface Coordinates (X,Y,Z)
  GWallSX      =  0.0_rk;
  GWallSY      =  0.0_rk;
  
  ! Global Wall Normal Vector (nwx,nwy,nwz)
  GWallNormalX =  0.0_rk;
  GWallNormalY =  0.0_rk;
  
  ! Global Shock-Wall Distance GShockH
  GShockH      =  0.0_rk;
    
  S_head     = R_head * (pi - 2.0_rk * theta_p_rad);
  
  S_flate    = (LModel - R_head*(1.0_rk - sin(theta_p_rad)))/cos(theta_p_rad);
  
  if(LModel <= R_head*(1.0_rk - sin(theta_p_rad))) then
    !write(*,*)"The model is too small, please check the input parameters"
    S_flate = 0.0_rk;
  endif

  S_total    = S_head + S_flate;

  sxi_nxr    = 0.5_rk * pi - theta_p_rad;  ! define the half head for the model

  ! For this wedge, we have
  delta      = R_head * 0.386 * exp(4.67 / Mach_Normal / Mach_Normal);
    Rc       = R_head * 1.386 * exp(1.8/(Mach_Normal - 1.0)**0.75);
  
  ! define the Heta grid
   eta_ay    = ymax * yim / (ymax - 2.d0 * yim);
   eta_by    = 1.d0 + 2.d0 * eta_ay / ymax;

   DO jc = 1,Ny
        eta = -1.d0 + 2.d0 * (jc - 1.d0)/(Ny - 1.d0);   
      Ytemp = 2.d0 * ( (1.d0 - tanh(sigma_y)) * (eta + 1.d0)/2.d0)/&
                     ( 1.d0 - tanh( sigma_y * (eta + 1.d0)/2.d0) ) - 1.d0;
    Heta(:,jc,:)= eta_ay * (1.d0 + Ytemp)/(eta_by - Ytemp);
   ENDDO
  !
  ! define the 
  xi_ax      = ximax * xim / (ximax - 2.d0 * xim);
  xi_bx      = 1.d0 + 2.d0 * xi_ax / ximax;
  DO ic = 1,Nx_head_hf
         xi = -1.d0 + 2.d0 * (ic - 1.d0)/(Nx_head_hf - 1.d0);
    !sxi(ic) = (xi + 1.d0) / 2.d0;
    sxi(ic) = xi_ax * ( 1.d0 + xi )/( xi_bx - xi );
  ENDDO

  DO ic = 1,Nx_head_hf
    sxi_total(ic) = - sxi(Nx_head_hf + 1 - ic);
  ENDDO

  DO ic = Nx_head_hf + 1,Nx_head
    sxi_total(ic) =   sxi(ic - Nx_head_hf + 1);
  ENDDO

  !% the first part
  !==============================================================================|
  !                                                                              |
  !                      Blunt Round 2D                                          |
  !                                                                              |
  !==============================================================================|
  If (Geometry_Type == 1)then
  DO ic = 1,Nx_head
    theta_lcl = sxi_total(ic) * sxi_nxr;
    GSxi_Surface(ic) = theta_lcl;
    GWallSX(ic) = R_head * (1.d0 - cos(theta_lcl));
    GWallSY(ic) = R_head * sin(theta_lcl);
    GWallNormalX(ic) = -cos(theta_lcl);
    GWallNormalY(ic) = sin(theta_lcl);
  ENDDO
!!===========================================================================================|
!!                                                                                           |
!!                  Blunt Parabola 2D  £¨x = 1/(2*R) * y^2£©                                 |
!!                                                                                           |
!!==========================================================================================!|
  else if(Geometry_Type == 2)then
      
  DO ic = 1,Nx_head
     theta_lcl = sxi_total(ic) * sxi_nxr;
     GSxi_Surface(ic) = theta_lcl;
     GWallSX(ic) = 1.d0/(2.d0*R_head) * (sxi_total(ic) * 2.d0 *sqrt(10.d0)*R_head)**2.d0;
     GWallSY(ic) = sxi_total(ic) * 2.d0 * sqrt(10.d0) * R_head;
     GWallNormalX(ic) = -1.d0 / sqrt((GWallSY(ic)/R_head)**2+1.d0);
     GWallNormalY(ic) = GWallSY(ic)/R_head/sqrt((GWallSY(ic)/R_head)**2+1.d0);
  ENDDO
  
  endif
!!==========================================================================================!|
  if( S_flate > 0.d0 ) then
    ! start ds1
    ds1 = R_head * (sxi_total(Nx_head) * sxi_nxr - sxi_total(Nx_head-1) * sxi_nxr);
   
    ds_uni = S_flate / (Nx_flate - 1.d0);
  
    ds2 = max(3*ds1,3*ds_uni);
  
    call SettingTransformation(xx_flateplate,S_flate,Nx_flate,ds1,ds2)
  

    ! the second part
  
    Do ic = Nx_head+1,Nx
     GSxi_Surface(ic) = GSxi_Surface(ic-1) + sxi_nxr / (2.d0 * Nx);
     GWallSX(ic) = GWallSX(Nx_head) + xx_flateplate(ic + 1 - Nx_head) * cos(theta_p_rad);
     GWallSY(ic) = GWallSY(Nx_head) + xx_flateplate(ic + 1 - Nx_head) * sin(theta_p_rad);
     GWallNormalX(ic) = -sin(theta_p_rad);
     GWallNormalY(ic) =  cos(theta_p_rad);
    enddo

  endif

  ! define the Shock angle
  call Calculate_ShockTheta(beta,theta_p_rad,Mach_Normal,Gamma)
  
  tan2 = tan(beta) * tan(beta);
  ! 
  if( theta_p_deg >= 0.5_rk) then
   ! the flate part is not horizontal
   do ic = 1,Nx
     call Calculate_ShockHeight(GShockH(ic),&
       GWallSX(ic), GWallSY(ic), GWallNormalX(ic), GWallNormalY(ic),delta, Rc, tan2)
   enddo
  else
      
    If (Geometry_Type == 1)then
   ! the flate part is horizontal
      ic = 1
      temp = R_head*R_head*tan2 &
           + 2.d0 * R_head * delta * tan2 &
           + delta * delta * tan2 &
           + 2.d0 * R_head * Rc &
           + 2.d0 * Rc * delta;
    shk_xgrid2  =  R_head;  
    shk_ygrid2  = -sqrt(temp);
    GShockH(ic) = sqrt((shk_xgrid2 - GWallSX(ic))**2.d0+(shk_ygrid2 - GWallSY(ic))**2.d0);

   do ic = 2,Nx_head-1
     call Calculate_ShockHeight(GShockH(ic),&
       GWallSX(ic), GWallSY(ic), GWallNormalX(ic), GWallNormalY(ic),delta, Rc, tan2)     
   enddo


   do ic = Nx_head,Nx 
     temp = GWallSX(ic)*GWallSX(ic)*tan2  &  
          + 2.d0 * GWallSX(ic) * delta * tan2  & 
          + delta * delta * tan2   &
          + 2.d0 * GWallSX(ic) * Rc  &
          + 2.d0 * Rc * delta;
     shk_ygrid2 =  sqrt(temp);
     shk_xgrid2 =  GWallSX(ic);
    GShockH(ic) = sqrt((shk_xgrid2 - GWallSX(ic))**2.d0+(shk_ygrid2 - GWallSY(ic))**2.d0); 
   enddo
   
  elseif (Geometry_Type == 2)then
       do ic = 1,Nx_head
             call Calculate_ShockHeight(GShockH(ic),&
             GWallSX(ic), GWallSY(ic), GWallNormalX(ic), GWallNormalY(ic),delta, Rc, tan2)     
     enddo
  endif
  
   endif 
  ! Define the zeta grid
  do kc = 1,Nz
    GWallSZ(kc) = Lz_start + REAL(kc - 1) * (Lz_end - Lz_start)/REAL(Nz - 1); 
  enddo
   
  !if(MyId == 0) then
  ! write(*,*)"The main node output surface Coordinates"
  ! !Check Points: Output WallSX and WallSY
  ! inquire(file="CheckFiles", exist=dir_exists)
  ! if (.not. dir_exists) then
  !   call system("mkdir -p CheckFiles")
  ! endif
  ! open(123,file="CheckFiles/SurfaceCoordinate.dat",status="replace")
  ! write(123,*)"VARIABLES=ic, WallSX, WallSY, ShockH, GSxi"
  !  do ic = 1,Nx
  !   write(123,*)ic,GWallSX(ic),GWallSY(ic),GShockH(ic),GSxi_Surface(ic)
  !  enddo 
  ! close(123) 
  !endif

  ! Setting the grid points along I,K direction
  do kc = 1,nz_local
   kc_global = K_offset(npz) + kc - 1
   do ic = 1,nx_local
          ic_global = I_offset(npx) + ic - 1
         WallSX(ic,: ) = GWallSX(ic_global);      ! Surface X grid
         WallSY(ic,: ) = GWallSY(ic_global);      ! Surface Y grid
         WallSZ(:, kc) = GWallSZ(kc_global);      ! Surface Z grid
    WallNormalX(ic,: ) = GWallNormalX(ic_global); ! Surface wallnormal vector X
    WallNormalY(ic,: ) = GWallNormalY(ic_global); ! Surface wallnormal vector Y
    WallNormalZ(:, : ) = 0.0_rk;                  ! Surface wallnormal vector Z
         ShockH(ic,: ) = GShockH(ic_global);      ! Shock Height
    Sxi_Surface(ic,: ) = GSxi_Surface(ic_global); ! Sxi surface
   ENDDO
  ENDDO
  
  Call Parallel_Exchange_Surface(WallSX)
  Call Parallel_Exchange_Surface(WallSY)
  Call Parallel_Exchange_Surface(WallSZ)
  Call Parallel_Exchange_Surface(WallNormalX)
  Call Parallel_Exchange_Surface(WallNormalY)
  ! The WallNormalZ is set to zero
  WallNormalZ = 0.0_rk;
  Call Parallel_Exchange_Surface(ShockH)
  Call Parallel_Exchange_Surface(Sxi_Surface)
  ! The initial shock velocity is set to zero
  ShockV = 0.0_rk;

  ! generate the grid points on local domain for X , Y and Z directions 3D
  DO kc = 1-overLAP,nz_local+overLAP
   DO jc = 1,Ny
    DO ic = 1-overLAP,nx_local+overLAP
      X_grid(ic,jc,kc) = WallSX(ic,kc) + WallNormalX(ic,kc) * ShockH(ic,kc) * Heta(ic,jc,kc);
      Y_grid(ic,jc,kc) = WallSY(ic,kc) + WallNormalY(ic,kc) * ShockH(ic,kc) * Heta(ic,jc,kc);
      Z_grid(ic,jc,kc) = WallSZ(ic,kc) + WallNormalZ(ic,kc) * ShockH(ic,kc) * Heta(ic,jc,kc);
    ENDDO
   ENDDO
  ENDDO
  
  ! Here we output the basic grids for tests and view
  ! we output the .pvts and .vts files for the paraview

  ! 
  call Parallel_Exchange(X_grid)
  call Parallel_Exchange(Y_grid)
  call Parallel_Exchange(Z_grid)
  
  if(MyId == 0) then
   write(*,*)"Output the initial grid" 
  endif

  call output_initial_grid

  if(MyId == 0) then
   write(*,*)"Output the initial grid finished" 
  endif

  ! Here we need to calculate some derivatives 
  ! with respect to the Wall Surface variables
   
  ! only the xi direction need parallel exchange

   CALL Cal_Deri_SurfDxi_5th_ce(WallSXdxi,WallSX)
   CALL Cal_Deri_SurfDxi_5th_ce(WallSYdxi,WallSY)
  ! CALL Cal_Deri_SurfDxi_5th_ce(WallSZdxi,WallSZ)
   WallSZdxi = 0.0_rk;

   CALL Parallel_Exchange_Surface(WallSXdxi)
   CALL Parallel_Exchange_Surface(WallSYdxi)

   !CALL Cal_Deri_SurfDzeta_5th_ce(WallSXdzeta,WallSX)
   WallSXdzeta = 0.0_rk;
   !CALL Cal_Deri_SurfDzeta_5th_ce(WallSYdzeta,WallSY)
   WallSYdzeta = 0.0_rk;
   !CALL Cal_Deri_SurfDzeta_5th_ce(WallSZdzeta,WallSZ)
   WallSZdzeta = REAL(Lz_end - Lz_start, kind = rk)/REAL(Nz - 1, kind = rk);   
   
   CALL Cal_Deri_SurfDxi_5th_ce(WallNormalXdxi,WallNormalX)
   CALL Cal_Deri_SurfDxi_5th_ce(WallNormalYdxi,WallNormalY)
  ! CALL Cal_Deri_SurfDxi_5th_ce(WallNormalZdxi,WallNormalZ)
   WallNormalZdxi = 0.0_rk;

   CALL Parallel_Exchange_Surface(WallNormalXdxi)
   CALL Parallel_Exchange_Surface(WallNormalYdxi)

  !
   WallNormalXdzeta = 0.0_rk;
   WallNormalYdzeta = 0.0_rk;
   WallNormalZdzeta = 0.0_rk; 

  !CALL Cal_Deri_1DDeta_5th_ce(Hetadeta,Heta)
   CALL Parallel_Exchange(Heta)

   CALL Cal_Deri_Dxi_5th_ce(HetaDxi,Heta)
   CALL Cal_Deri_Deta_5th_ce(Hetadeta,Heta) 
   CALL Cal_Deri_Dzeta_5th_ce(HetaDzeta,Heta)

  ! Output some files for checking
  !if(MyId == 0) then
  ! write(*,*)"The main node output surface Coordinates derivatives"
  ! !Check Points: Output WallSX and WallSY
  ! open(123,file="CheckFiles/SurfaceCoordinateDiff.dat",status="replace")
  ! write(123,"(A)")"VARIABLES=WallSX,WallSXdxi,WallSY,WallSYdxi,WallSZ,&
  !                 & WallNormalX,WallNormalY,WallNormalXdxi,WallNormalYdxi"
  ! close(123)
  !
  ! open(123,file="CheckFiles/WallNormal.dat",status="replace")
  ! write(123,"(A)")"VARIABLES=jc,Heta,Hetadeta"
  ! close(123)
  !endif

end subroutine Initial_Grid

! This subroutine calculate the local shock height 2D
!SUBROUTINE Calculate_ShockHeight(shk_Height,WallSX, WallSY, WallNormalX, WallNormalY,delta, Rc, tan2)
!  use SF_Constant,  only:rk
!  implicit none
!  real( kind = rk ) :: WallSX, WallSY, WallNormalX, WallNormalY
!  real( kind = rk ) :: delta, Rc, tan2
!  real( kind = rk ) :: shk_Height
!  real( kind = rk ) :: a,b,c,tempY1
!  real( kind = rk ) :: shk_ygrid2,shk_xgrid2
!
!   a = WallNormalX * WallNormalX * tan2 - WallNormalY * WallNormalY;
!   b =   2.d0 * delta * WallNormalX * WallNormalX * tan2 &
!       + 2.d0 * Rc * WallNormalX * WallNormalX &
!       - 2.d0 * WallNormalX * WallNormalY * WallSY &
!       + 2.d0 * WallNormalY * WallNormalY * WallSX;
!   c = delta * delta * tan2 * WallNormalX * WallNormalX &
!       + 2.d0 * Rc * delta * WallNormalX * WallNormalX &
!       - WallNormalX * WallNormalX * WallSY * WallSY &
!       + 2.d0 * WallNormalX * WallNormalY * WallSX * WallSY &
!       - WallNormalY * WallNormalY * WallSX * WallSX;
! 
!    tempY1 = (-b + sqrt(b*b - 4.d0 * a * c))/(2.d0 * a);
! 
!   shk_ygrid2 = WallSY + WallNormalY / WallNormalX * tempY1 - WallSX * WallNormalY/WallNormalX;
!   shk_xgrid2 = Rc/tan2 * (sqrt(1.d0 + shk_ygrid2 * shk_ygrid2 * tan2/(Rc * Rc)) - 1.d0) - delta;
!   shk_Height = sqrt((shk_xgrid2 - WallSX)**2.d0+(shk_ygrid2 - WallSY)**2.d0);
!
!END SUBROUTINE Calculate_ShockHeight
!
!! This subroutine calculate the grid distribution for a smooth transformation
!SUBROUTINE SettingTransformation(XX,Length,Nx,dx1,dx2)
!  ! This subroutine calculate a smooth distributions
!  ! 
!  use SF_Constant,    only:ik,rk
!  implicit none
!  integer( kind = ik )::Nx
!  real( kind = rk ):: Length,dx1,dx2
!  real( kind = rk ):: XX(1:Nx)
!
!  real( kind = rk )::xuniform,Ah1,Sh0,Sh1
!  integer(kind=ik ):: ic
!
!  DO ic = 1,Nx
!    xuniform = ( ic - 1.d0 )/( Nx - 1.d0 );
!    Ah1 = ( 1.d0 - 2.d0 * ( xuniform - 1.d0 )) * xuniform * xuniform;
!    Sh0 = xuniform * (xuniform - 1.d0)**2;
!    Sh1 = (xuniform - 1.d0) * xuniform * xuniform;
!    XX(ic) = Length * Ah1 + dx1 * (Nx - 1.d0) * Sh0 + dx2 * (Nx - 1.d0) * Sh1;
!  ENDDO
!
!END SUBROUTINE SettingTransformation
!
!! This subroutine calculate the local shock angle 2D
!SUBROUTINE Calculate_ShockTheta(beta,theta_p_rad,Mach_n,Gamma)
!   use SF_Constant, only:rk
!   implicit none
!   real(kind = rk)::beta,theta_p_rad,Mach_n,Gamma
!   real(kind = rk)::F,FP,FM,DFDB,EPS
!   real(kind = rk)::Dbeta,TINY,FunMyCase
!
!   beta = max(tan(theta_p_rad),2.0e-8_rk);
!   Dbeta = 1.e-8;
!   TINY = 1.0e-14;
!   EPS = 1.d0;   
!   do while(eps > tiny)
!      F  = FunMyCase(beta,Mach_n,Gamma) - tan(theta_p_rad);
!      FP = FunMyCase(beta+Dbeta,Mach_n,Gamma);
!      FM = FunMyCase(beta-Dbeta,Mach_n,Gamma);
!    DFDB = (FP - FM) / (2.0 * Dbeta);
!     EPS = abs(F / DFDB);
!    beta = beta - F / DFDB;      
!   enddo
!
!END SUBROUTINE Calculate_ShockTheta
!
!function FunMyCase(beta,Ma,Gamma)
!  use SF_Constant,    only:rk
!  implicit none
!  real( kind = rk )::FunMyCase,beta,Ma,Gamma
!  real( kind = rk )::FuncCase1,FuncCase2
!      FuncCase1 = Ma*Ma*sin(beta)*sin(beta) - 1.d0;
!      FuncCase2 = Ma*Ma*(Gamma + cos(2*beta)) + 2.d0;
!      FunMyCase = 2/tan(beta) * FuncCase1 / FuncCase2;
!end function