!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (bugfix_servletAD) -  4 Jan 2024 17:44
!
!  Differentiation of linearized_shockbc in forward (tangent) mode:
!   variations   of useful results: srho sp st su sv sw
!   with respect to varying inputs: rho_free shockh shockv u_free
!                w_free p_free v_free
!   RW status of diff variables: rho_free:in shockh:in shockv:in
!                u_free:in w_free:in srho:out sp:out p_free:in
!                st:out su:out sv:out sw:out v_free:in
SUBROUTINE LINEARIZED_SHOCKBC_D(shockh, shockhd, shockv, shockvd, &
& rho_free, rho_freed, u_free, u_freed, v_free, v_freed, w_free, w_freed&
& , p_free, p_freed, nx_local, ny_local, nz_local, overlap, gamma, &
& mach_ref, re_ref, wallsx, wallsy, wallsz, k_infty, epsilon, pert_type&
& , wallsxdxi, wallsydxi, wallszdxi, wallsxdzeta, wallsydzeta, &
& wallszdzeta, wallnormalx, wallnormaly, wallnormalz, wallnormalxdxi, &
& wallnormalydxi, wallnormalzdxi, wallnormalxdzeta, wallnormalydzeta, &
& wallnormalzdzeta, heta, hetadxi, hetadzeta, hetadeta, srho, srhod, su&
& , sud, sv, svd, sw, swd, sp, spd, st, std)

use MPI_GLOBAL,   only: Parallel_Exchange_Surface, Parallel_Exchange,&
                      & Parallel_Exchange_NumVar,&
                      & npx, npx0, npz, npz0

  IMPLICIT NONE
  INTEGER*4, INTENT(IN) :: nx_local, ny_local, nz_local, overlap, &
& pert_type
  REAL*8, INTENT(IN) :: gamma, mach_ref, re_ref, epsilon, k_infty
  REAL*8, INTENT(IN) :: rho_free(1-overlap:nx_local+overlap, ny_local, 1&
& -overlap:nz_local+overlap)
  REAL*8, INTENT(IN) :: rho_freed(1-overlap:nx_local+overlap, ny_local, &
& 1-overlap:nz_local+overlap)
  REAL*8, INTENT(IN) :: u_free(1-overlap:nx_local+overlap, ny_local, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(IN) :: u_freed(1-overlap:nx_local+overlap, ny_local, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(IN) :: v_free(1-overlap:nx_local+overlap, ny_local, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(IN) :: v_freed(1-overlap:nx_local+overlap, ny_local, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(IN) :: w_free(1-overlap:nx_local+overlap, ny_local, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(IN) :: w_freed(1-overlap:nx_local+overlap, ny_local, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(IN) :: p_free(1-overlap:nx_local+overlap, ny_local, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(IN) :: p_freed(1-overlap:nx_local+overlap, ny_local, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(IN) :: shockh(1-overlap:nx_local+overlap, 1-overlap:&
& nz_local+overlap)
  REAL*8, INTENT(IN) :: shockhd(1-overlap:nx_local+overlap, 1-overlap:&
& nz_local+overlap)
  REAL*8, INTENT(IN) :: shockv(1-overlap:nx_local+overlap, 1-overlap:&
& nz_local+overlap)
  REAL*8, INTENT(IN) :: shockvd(1-overlap:nx_local+overlap, 1-overlap:&
& nz_local+overlap)
  REAL*8, INTENT(IN) :: wallsx(1-overlap:nx_local+overlap, 1-overlap:&
& nz_local+overlap)
  REAL*8, INTENT(IN) :: wallsy(1-overlap:nx_local+overlap, 1-overlap:&
& nz_local+overlap)
  REAL*8, INTENT(IN) :: wallsz(1-overlap:nx_local+overlap, 1-overlap:&
& nz_local+overlap)
  REAL*8, INTENT(IN) :: wallsxdxi(1-overlap:nx_local+overlap, 1-overlap:&
& nz_local+overlap)
  REAL*8, INTENT(IN) :: wallsydxi(1-overlap:nx_local+overlap, 1-overlap:&
& nz_local+overlap)
  REAL*8, INTENT(IN) :: wallszdxi(1-overlap:nx_local+overlap, 1-overlap:&
& nz_local+overlap)
  REAL*8, INTENT(IN) :: wallsxdzeta(1-overlap:nx_local+overlap, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(IN) :: wallsydzeta(1-overlap:nx_local+overlap, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(IN) :: wallszdzeta(1-overlap:nx_local+overlap, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(IN) :: wallnormalx(1-overlap:nx_local+overlap, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(IN) :: wallnormaly(1-overlap:nx_local+overlap, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(IN) :: wallnormalz(1-overlap:nx_local+overlap, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(IN) :: wallnormalxdxi(1-overlap:nx_local+overlap, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(IN) :: wallnormalydxi(1-overlap:nx_local+overlap, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(IN) :: wallnormalzdxi(1-overlap:nx_local+overlap, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(IN) :: wallnormalxdzeta(1-overlap:nx_local+overlap, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(IN) :: wallnormalydzeta(1-overlap:nx_local+overlap, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(IN) :: wallnormalzdzeta(1-overlap:nx_local+overlap, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(IN) :: heta(1-overlap:nx_local+overlap, ny_local, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(IN) :: hetadxi(1-overlap:nx_local+overlap, ny_local, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(IN) :: hetadeta(1-overlap:nx_local+overlap, ny_local, 1&
& -overlap:nz_local+overlap)
  REAL*8, INTENT(IN) :: hetadzeta(1-overlap:nx_local+overlap, ny_local, &
& 1-overlap:nz_local+overlap)
  REAL*8, INTENT(OUT) :: srho(1-overlap:nx_local+overlap, ny_local, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(OUT) :: srhod(1-overlap:nx_local+overlap, ny_local, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(OUT) :: su(1-overlap:nx_local+overlap, ny_local, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(OUT) :: sud(1-overlap:nx_local+overlap, ny_local, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(OUT) :: sv(1-overlap:nx_local+overlap, ny_local, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(OUT) :: svd(1-overlap:nx_local+overlap, ny_local, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(OUT) :: sw(1-overlap:nx_local+overlap, ny_local, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(OUT) :: swd(1-overlap:nx_local+overlap, ny_local, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(OUT) :: sp(1-overlap:nx_local+overlap, ny_local, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(OUT) :: spd(1-overlap:nx_local+overlap, ny_local, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(OUT) :: st(1-overlap:nx_local+overlap, ny_local, 1-&
& overlap:nz_local+overlap)
  REAL*8, INTENT(OUT) :: std(1-overlap:nx_local+overlap, ny_local, 1-&
& overlap:nz_local+overlap)
  INTEGER :: ic, jc, kc
  REAL*8, DIMENSION(:, :, :), ALLOCATABLE :: x_grid, y_grid, z_grid
  REAL*8, DIMENSION(:, :), ALLOCATABLE :: shockhdzeta, shockhdxi, &
& shockvdzeta, shockvdxi
  REAL*8, DIMENSION(:, :), ALLOCATABLE :: shockhdzetad, shockhdxid, &
& shockvdzetad, shockvdxid
  REAL*8, DIMENSION(:, :, :), ALLOCATABLE :: dxdxi, dydxi, dzdxi, dxdeta&
& , dydeta, dzdeta, dxdzeta, dydzeta, dzdzeta
  REAL*8, DIMENSION(:, :, :), ALLOCATABLE :: dxdxid, dydxid, dzdxid, &
& dxdetad, dydetad, dzdetad, dxdzetad, dydzetad, dzdzetad
  REAL*8, DIMENSION(:, :, :), ALLOCATABLE :: jaco, invjacodt
  REAL*8, DIMENSION(:, :, :), ALLOCATABLE :: jacod
  REAL*8, DIMENSION(:, :, :), ALLOCATABLE :: dxidx, dxidy, dxidz, detadx&
& , detady, detadz, dzetadx, dzetady, dzetadz
  REAL*8, DIMENSION(:, :, :), ALLOCATABLE :: detadxd, detadyd, detadzd
  REAL*8, DIMENSION(:, :, :), ALLOCATABLE :: nablaxi, nablaeta, &
& nablazeta
  REAL*8, DIMENSION(:, :, :), ALLOCATABLE :: nablaetad
  REAL*8, DIMENSION(:, :), ALLOCATABLE :: shocknormalx, shocknormaly, &
& shocknormalz
  REAL*8, DIMENSION(:, :), ALLOCATABLE :: shocknormalxd, shocknormalyd, &
& shocknormalzd
  REAL*8 :: xxitau, yxitau, zxitau, xetatau, yetatau, zetatau, xzetatau&
& , yzetatau, zzetatau, temp
  REAL*8 :: tempd
  REAL*8 :: delta_inf, delta2
  REAL*8 :: delta_infd, delta2d
  INTRINSIC SQRT
  REAL*8 :: arg1
  REAL*8 :: arg1d
  REAL*8 :: temp0
  REAL*8 :: temp1
  REAL*8 :: temp2
  ALLOCATE(x_grid(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(y_grid(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(z_grid(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(shockhdzetad(1-overlap:nx_local+overlap, 1-overlap:nz_local+&
& overlap))
  ALLOCATE(shockhdzeta(1-overlap:nx_local+overlap, 1-overlap:nz_local+&
& overlap))
  ALLOCATE(shockhdxid(1-overlap:nx_local+overlap, 1-overlap:nz_local+&
& overlap))
  ALLOCATE(shockhdxi(1-overlap:nx_local+overlap, 1-overlap:nz_local+&
& overlap))
  ALLOCATE(shockvdzetad(1-overlap:nx_local+overlap, 1-overlap:nz_local+&
& overlap))
  ALLOCATE(shockvdzeta(1-overlap:nx_local+overlap, 1-overlap:nz_local+&
& overlap))
  ALLOCATE(shockvdxid(1-overlap:nx_local+overlap, 1-overlap:nz_local+&
& overlap))
  ALLOCATE(shockvdxi(1-overlap:nx_local+overlap, 1-overlap:nz_local+&
& overlap))
  ALLOCATE(dxdxid(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(dxdxi(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(dydxid(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(dydxi(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(dzdxid(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(dzdxi(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(dxdetad(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(dxdeta(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(dydetad(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(dydeta(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(dzdetad(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(dzdeta(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(dxdzetad(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(dxdzeta(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(dydzetad(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(dydzeta(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(dzdzetad(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(dzdzeta(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(jacod(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(jaco(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(invjacodt(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(dxidx(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(dxidy(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(dxidz(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(detadxd(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(detadx(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(detadyd(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(detady(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(detadzd(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(detadz(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(dzetadx(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(dzetady(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(dzetadz(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(nablaxi(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(nablaetad(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(nablaeta(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(nablazeta(1-overlap:nx_local+overlap, 1:ny_local, 1-overlap:&
& nz_local+overlap))
  ALLOCATE(shocknormalxd(1-overlap:nx_local+overlap, 1-overlap:nz_local+&
& overlap))
  ALLOCATE(shocknormalx(1-overlap:nx_local+overlap, 1-overlap:nz_local+&
& overlap))
  ALLOCATE(shocknormalyd(1-overlap:nx_local+overlap, 1-overlap:nz_local+&
& overlap))
  ALLOCATE(shocknormaly(1-overlap:nx_local+overlap, 1-overlap:nz_local+&
& overlap))
  ALLOCATE(shocknormalzd(1-overlap:nx_local+overlap, 1-overlap:nz_local+&
& overlap))
  ALLOCATE(shocknormalz(1-overlap:nx_local+overlap, 1-overlap:nz_local+&
& overlap))
  DO kc=1-overlap,nz_local+overlap
    DO jc=1,ny_local
      DO ic=1-overlap,nx_local+overlap
        x_grid(ic, jc, kc) = wallsx(ic, kc) + wallnormalx(ic, kc)*shockh&
&         (ic, kc)*heta(ic, jc, kc)
        y_grid(ic, jc, kc) = wallsy(ic, kc) + wallnormaly(ic, kc)*shockh&
&         (ic, kc)*heta(ic, jc, kc)
        z_grid(ic, jc, kc) = wallsz(ic, kc) + wallnormalz(ic, kc)*shockh&
&         (ic, kc)*heta(ic, jc, kc)
      END DO
    END DO
  END DO
CALL Parallel_Exchange(X_grid)
CALL Parallel_Exchange(Y_grid)
CALL Parallel_Exchange(Z_grid)  

CALL Parallel_Exchange_surface(shockH)
CALL Parallel_Exchange_surface(shockHd)
CALL Parallel_Exchange_surface(shockV)
CALL Parallel_Exchange_surface(shockVd)

  CALL CALCULATE_FDXI_SURF_CE_D_un_BC(shockhdxi, shockhdxid, shockh, shockhd, &
&                         nx_local, nz_local, overlap, npx, npx0)
  CALL CALCULATE_FDXI_SURF_CE_D_un_BC(shockvdxi, shockvdxid, shockv, shockvd, &
&                         nx_local, nz_local, overlap, npx, npx0)
  CALL CALCULATE_FDZETA_SURF_CE_D_un_BC(shockhdzeta, shockhdzetad, shockh, &
&                           shockhd, nx_local, nz_local, overlap, npz, npz0)
  CALL CALCULATE_FDZETA_SURF_CE_D_un_BC(shockvdzeta, shockvdzetad, shockv, &
&                           shockvd, nx_local, nz_local, overlap, npz, npz0)
  CALL Parallel_Exchange_surface(shockhdxi)
  CALL Parallel_Exchange_surface(shockhdxid)
  CALL Parallel_Exchange_surface(shockvdxi)
  CALL Parallel_Exchange_surface(shockvdxid)
  CALL Parallel_Exchange_surface(shockhdzeta)
  CALL Parallel_Exchange_surface(shockhdzetad)
  CALL Parallel_Exchange_surface(shockvdzeta)
  CALL Parallel_Exchange_surface(shockvdzetad)
  
  DO kc=1-overlap,nz_local+overlap
    DO jc=1,ny_local
      DO ic=1-overlap,nx_local+overlap
        dxdxid(ic, jc, kc) = heta(ic, jc, kc)*(wallnormalxdxi(ic, kc)*&
&         shockhd(ic, kc)+wallnormalx(ic, kc)*shockhdxid(ic, kc)) + &
&         hetadxi(ic, jc, kc)*wallnormalx(ic, kc)*shockhd(ic, kc)
        dxdxi(ic, jc, kc) = wallsxdxi(ic, kc) + (wallnormalxdxi(ic, kc)*&
&         shockh(ic, kc)+wallnormalx(ic, kc)*shockhdxi(ic, kc))*heta(ic&
&         , jc, kc) + wallnormalx(ic, kc)*shockh(ic, kc)*hetadxi(ic, jc&
&         , kc)
        xxitau = (wallnormalxdxi(ic, kc)*shockv(ic, kc)+wallnormalx(ic, &
&         kc)*shockvdxi(ic, kc))*heta(ic, jc, kc) + wallnormalx(ic, kc)*&
&         shockv(ic, kc)*hetadxi(ic, jc, kc)
        dydxid(ic, jc, kc) = heta(ic, jc, kc)*(wallnormalydxi(ic, kc)*&
&         shockhd(ic, kc)+wallnormaly(ic, kc)*shockhdxid(ic, kc)) + &
&         hetadxi(ic, jc, kc)*wallnormaly(ic, kc)*shockhd(ic, kc)
        dydxi(ic, jc, kc) = wallsydxi(ic, kc) + (wallnormalydxi(ic, kc)*&
&         shockh(ic, kc)+wallnormaly(ic, kc)*shockhdxi(ic, kc))*heta(ic&
&         , jc, kc) + wallnormaly(ic, kc)*shockh(ic, kc)*hetadxi(ic, jc&
&         , kc)
        yxitau = (wallnormalydxi(ic, kc)*shockv(ic, kc)+wallnormaly(ic, &
&         kc)*shockvdxi(ic, kc))*heta(ic, jc, kc) + wallnormaly(ic, kc)*&
&         shockv(ic, kc)*hetadxi(ic, jc, kc)
        dzdxid(ic, jc, kc) = heta(ic, jc, kc)*(wallnormalzdxi(ic, kc)*&
&         shockhd(ic, kc)+wallnormalz(ic, kc)*shockhdxid(ic, kc)) + &
&         hetadxi(ic, jc, kc)*wallnormalz(ic, kc)*shockhd(ic, kc)
        dzdxi(ic, jc, kc) = wallszdxi(ic, kc) + (wallnormalzdxi(ic, kc)*&
&         shockh(ic, kc)+wallnormalz(ic, kc)*shockhdxi(ic, kc))*heta(ic&
&         , jc, kc) + wallnormalz(ic, kc)*shockh(ic, kc)*hetadxi(ic, jc&
&         , kc)
        zxitau = (wallnormalzdxi(ic, kc)*shockv(ic, kc)+wallnormalz(ic, &
&         kc)*shockvdxi(ic, kc))*heta(ic, jc, kc) + wallnormalz(ic, kc)*&
&         shockv(ic, kc)*hetadxi(ic, jc, kc)
        dxdetad(ic, jc, kc) = hetadeta(ic, jc, kc)*wallnormalx(ic, kc)*&
&         shockhd(ic, kc)
        dxdeta(ic, jc, kc) = wallnormalx(ic, kc)*shockh(ic, kc)*hetadeta&
&         (ic, jc, kc)
        dydetad(ic, jc, kc) = hetadeta(ic, jc, kc)*wallnormaly(ic, kc)*&
&         shockhd(ic, kc)
        dydeta(ic, jc, kc) = wallnormaly(ic, kc)*shockh(ic, kc)*hetadeta&
&         (ic, jc, kc)
        dzdetad(ic, jc, kc) = hetadeta(ic, jc, kc)*wallnormalz(ic, kc)*&
&         shockhd(ic, kc)
        dzdeta(ic, jc, kc) = wallnormalz(ic, kc)*shockh(ic, kc)*hetadeta&
&         (ic, jc, kc)
        xetatau = wallnormalx(ic, kc)*shockv(ic, kc)*hetadeta(ic, jc, kc&
&         )
        yetatau = wallnormaly(ic, kc)*shockv(ic, kc)*hetadeta(ic, jc, kc&
&         )
        zetatau = wallnormalz(ic, kc)*shockv(ic, kc)*hetadeta(ic, jc, kc&
&         )
        dxdzetad(ic, jc, kc) = heta(ic, jc, kc)*(wallnormalxdzeta(ic, kc&
&         )*shockhd(ic, kc)+wallnormalx(ic, kc)*shockhdzetad(ic, kc)) + &
&         hetadzeta(ic, jc, kc)*wallnormalx(ic, kc)*shockhd(ic, kc)
        dxdzeta(ic, jc, kc) = wallsxdzeta(ic, kc) + (wallnormalxdzeta(ic&
&         , kc)*shockh(ic, kc)+wallnormalx(ic, kc)*shockhdzeta(ic, kc))*&
&         heta(ic, jc, kc) + wallnormalx(ic, kc)*shockh(ic, kc)*&
&         hetadzeta(ic, jc, kc)
        xzetatau = (wallnormalxdzeta(ic, kc)*shockv(ic, kc)+wallnormalx(&
&         ic, kc)*shockvdzeta(ic, kc))*heta(ic, jc, kc) + wallnormalx(ic&
&         , kc)*shockv(ic, kc)*hetadzeta(ic, jc, kc)
        dydzetad(ic, jc, kc) = heta(ic, jc, kc)*(wallnormalydzeta(ic, kc&
&         )*shockhd(ic, kc)+wallnormaly(ic, kc)*shockhdzetad(ic, kc)) + &
&         hetadzeta(ic, jc, kc)*wallnormaly(ic, kc)*shockhd(ic, kc)
        dydzeta(ic, jc, kc) = wallsydzeta(ic, kc) + (wallnormalydzeta(ic&
&         , kc)*shockh(ic, kc)+wallnormaly(ic, kc)*shockhdzeta(ic, kc))*&
&         heta(ic, jc, kc) + wallnormaly(ic, kc)*shockh(ic, kc)*&
&         hetadzeta(ic, jc, kc)
        yzetatau = (wallnormalydzeta(ic, kc)*shockv(ic, kc)+wallnormaly(&
&         ic, kc)*shockvdzeta(ic, kc))*heta(ic, jc, kc) + wallnormaly(ic&
&         , kc)*shockv(ic, kc)*hetadzeta(ic, jc, kc)
        dzdzetad(ic, jc, kc) = heta(ic, jc, kc)*(wallnormalzdzeta(ic, kc&
&         )*shockhd(ic, kc)+wallnormalz(ic, kc)*shockhdzetad(ic, kc)) + &
&         hetadzeta(ic, jc, kc)*wallnormalz(ic, kc)*shockhd(ic, kc)
        dzdzeta(ic, jc, kc) = wallszdzeta(ic, kc) + (wallnormalzdzeta(ic&
&         , kc)*shockh(ic, kc)+wallnormalz(ic, kc)*shockhdzeta(ic, kc))*&
&         heta(ic, jc, kc) + wallnormalz(ic, kc)*shockh(ic, kc)*&
&         hetadzeta(ic, jc, kc)
        zzetatau = (wallnormalzdzeta(ic, kc)*shockv(ic, kc)+wallnormalz(&
&         ic, kc)*shockvdzeta(ic, kc))*heta(ic, jc, kc) + wallnormalz(ic&
&         , kc)*shockv(ic, kc)*hetadzeta(ic, jc, kc)
        temp0 = dydeta(ic, jc, kc)*dzdzeta(ic, jc, kc) - dzdeta(ic, jc, &
&         kc)*dydzeta(ic, jc, kc)
        temp1 = dydzeta(ic, jc, kc)*dzdxi(ic, jc, kc) - dydxi(ic, jc, kc&
&         )*dzdzeta(ic, jc, kc)
        temp2 = dydxi(ic, jc, kc)*dzdeta(ic, jc, kc) - dydeta(ic, jc, kc&
&         )*dzdxi(ic, jc, kc)
        tempd = temp0*dxdxid(ic, jc, kc) + dxdxi(ic, jc, kc)*(dzdzeta(ic&
&         , jc, kc)*dydetad(ic, jc, kc)+dydeta(ic, jc, kc)*dzdzetad(ic, &
&         jc, kc)-dydzeta(ic, jc, kc)*dzdetad(ic, jc, kc)-dzdeta(ic, jc&
&         , kc)*dydzetad(ic, jc, kc)) + temp1*dxdetad(ic, jc, kc) + &
&         dxdeta(ic, jc, kc)*(dzdxi(ic, jc, kc)*dydzetad(ic, jc, kc)+&
&         dydzeta(ic, jc, kc)*dzdxid(ic, jc, kc)-dzdzeta(ic, jc, kc)*&
&         dydxid(ic, jc, kc)-dydxi(ic, jc, kc)*dzdzetad(ic, jc, kc)) + &
&         temp2*dxdzetad(ic, jc, kc) + dxdzeta(ic, jc, kc)*(dzdeta(ic, &
&         jc, kc)*dydxid(ic, jc, kc)+dydxi(ic, jc, kc)*dzdetad(ic, jc, &
&         kc)-dzdxi(ic, jc, kc)*dydetad(ic, jc, kc)-dydeta(ic, jc, kc)*&
&         dzdxid(ic, jc, kc))
        temp = dxdxi(ic, jc, kc)*temp0 + dxdeta(ic, jc, kc)*temp1 + &
&         dxdzeta(ic, jc, kc)*temp2
        jacod(ic, jc, kc) = -(tempd/temp**2)
        jaco(ic, jc, kc) = 1.0d0/temp
        invjacodt(ic, jc, kc) = xxitau*(dydeta(ic, jc, kc)*dzdzeta(ic, &
&         jc, kc)-dzdeta(ic, jc, kc)*dydzeta(ic, jc, kc)) + xetatau*(&
&         dydzeta(ic, jc, kc)*dzdxi(ic, jc, kc)-dydxi(ic, jc, kc)*&
&         dzdzeta(ic, jc, kc)) + xzetatau*(dydxi(ic, jc, kc)*dzdeta(ic, &
&         jc, kc)-dydeta(ic, jc, kc)*dzdxi(ic, jc, kc)) + dxdxi(ic, jc, &
&         kc)*(yetatau*dzdzeta(ic, jc, kc)-zetatau*dydzeta(ic, jc, kc)) &
&         + dxdeta(ic, jc, kc)*(yzetatau*dzdxi(ic, jc, kc)-yxitau*&
&         dzdzeta(ic, jc, kc)) + dxdzeta(ic, jc, kc)*(yxitau*dzdeta(ic, &
&         jc, kc)-yetatau*dzdxi(ic, jc, kc)) + dxdxi(ic, jc, kc)*(dydeta&
&         (ic, jc, kc)*zzetatau-dzdeta(ic, jc, kc)*yzetatau) + dxdeta(ic&
&         , jc, kc)*(dydzeta(ic, jc, kc)*zxitau-dydxi(ic, jc, kc)*&
&         zzetatau) + dxdzeta(ic, jc, kc)*(dydxi(ic, jc, kc)*zetatau-&
&         dydeta(ic, jc, kc)*zxitau)
        dxidx(ic, jc, kc) = jaco(ic, jc, kc)*(dydeta(ic, jc, kc)*dzdzeta&
&         (ic, jc, kc)-dydzeta(ic, jc, kc)*dzdeta(ic, jc, kc))
        dxidy(ic, jc, kc) = -(jaco(ic, jc, kc)*(dxdeta(ic, jc, kc)*&
&         dzdzeta(ic, jc, kc)-dzdeta(ic, jc, kc)*dxdzeta(ic, jc, kc)))
        dxidz(ic, jc, kc) = jaco(ic, jc, kc)*(dxdeta(ic, jc, kc)*dydzeta&
&         (ic, jc, kc)-dydeta(ic, jc, kc)*dxdzeta(ic, jc, kc))
        temp2 = dydxi(ic, jc, kc)*dzdzeta(ic, jc, kc) - dzdxi(ic, jc, kc&
&         )*dydzeta(ic, jc, kc)
        detadxd(ic, jc, kc) = -(temp2*jacod(ic, jc, kc)+jaco(ic, jc, kc)&
&         *(dzdzeta(ic, jc, kc)*dydxid(ic, jc, kc)+dydxi(ic, jc, kc)*&
&         dzdzetad(ic, jc, kc)-dydzeta(ic, jc, kc)*dzdxid(ic, jc, kc)-&
&         dzdxi(ic, jc, kc)*dydzetad(ic, jc, kc)))
        detadx(ic, jc, kc) = -(jaco(ic, jc, kc)*temp2)
        temp2 = dxdxi(ic, jc, kc)*dzdzeta(ic, jc, kc) - dzdxi(ic, jc, kc&
&         )*dxdzeta(ic, jc, kc)
        detadyd(ic, jc, kc) = temp2*jacod(ic, jc, kc) + jaco(ic, jc, kc)&
&         *(dzdzeta(ic, jc, kc)*dxdxid(ic, jc, kc)+dxdxi(ic, jc, kc)*&
&         dzdzetad(ic, jc, kc)-dxdzeta(ic, jc, kc)*dzdxid(ic, jc, kc)-&
&         dzdxi(ic, jc, kc)*dxdzetad(ic, jc, kc))
        detady(ic, jc, kc) = jaco(ic, jc, kc)*temp2
        temp2 = dxdxi(ic, jc, kc)*dydzeta(ic, jc, kc) - dydxi(ic, jc, kc&
&         )*dxdzeta(ic, jc, kc)
        detadzd(ic, jc, kc) = -(temp2*jacod(ic, jc, kc)+jaco(ic, jc, kc)&
&         *(dydzeta(ic, jc, kc)*dxdxid(ic, jc, kc)+dxdxi(ic, jc, kc)*&
&         dydzetad(ic, jc, kc)-dxdzeta(ic, jc, kc)*dydxid(ic, jc, kc)-&
&         dydxi(ic, jc, kc)*dxdzetad(ic, jc, kc)))
        detadz(ic, jc, kc) = -(jaco(ic, jc, kc)*temp2)
        dzetadx(ic, jc, kc) = jaco(ic, jc, kc)*(dydxi(ic, jc, kc)*dzdeta&
&         (ic, jc, kc)-dzdxi(ic, jc, kc)*dydeta(ic, jc, kc))
        dzetady(ic, jc, kc) = -(jaco(ic, jc, kc)*(dxdxi(ic, jc, kc)*&
&         dzdeta(ic, jc, kc)-dzdxi(ic, jc, kc)*dxdeta(ic, jc, kc)))
        dzetadz(ic, jc, kc) = jaco(ic, jc, kc)*(dxdxi(ic, jc, kc)*dydeta&
&         (ic, jc, kc)-dydxi(ic, jc, kc)*dxdeta(ic, jc, kc))
        arg1 = dxidx(ic, jc, kc)*dxidx(ic, jc, kc) + dxidy(ic, jc, kc)*&
&         dxidy(ic, jc, kc) + dxidz(ic, jc, kc)*dxidz(ic, jc, kc)
        nablaxi(ic, jc, kc) = SQRT(arg1)
        arg1d = 2*detadx(ic, jc, kc)*detadxd(ic, jc, kc) + 2*detady(ic, &
&         jc, kc)*detadyd(ic, jc, kc) + 2*detadz(ic, jc, kc)*detadzd(ic&
&         , jc, kc)
        arg1 = detadx(ic, jc, kc)*detadx(ic, jc, kc) + detady(ic, jc, kc&
&         )*detady(ic, jc, kc) + detadz(ic, jc, kc)*detadz(ic, jc, kc)
        temp2 = SQRT(arg1)
        IF (arg1 .EQ. 0.0) THEN
          nablaetad(ic, jc, kc) = 0.0_8
        ELSE
          nablaetad(ic, jc, kc) = arg1d/(2.0*temp2)
        END IF
        nablaeta(ic, jc, kc) = temp2
        arg1 = dzetadx(ic, jc, kc)*dzetadx(ic, jc, kc) + dzetady(ic, jc&
&         , kc)*dzetady(ic, jc, kc) + dzetadz(ic, jc, kc)*dzetadz(ic, jc&
&         , kc)
        nablazeta(ic, jc, kc) = SQRT(arg1)
      END DO
    END DO
  END DO
  jc = ny_local
  DO kc=1-overlap,nz_local+overlap
    DO ic=1-overlap,nx_local+overlap
      temp2 = detadx(ic, jc, kc)/nablaeta(ic, jc, kc)
      shocknormalxd(ic, kc) = (detadxd(ic, jc, kc)-temp2*nablaetad(ic, &
&       jc, kc))/nablaeta(ic, jc, kc)
      shocknormalx(ic, kc) = temp2
      temp2 = detady(ic, jc, kc)/nablaeta(ic, jc, kc)
      shocknormalyd(ic, kc) = (detadyd(ic, jc, kc)-temp2*nablaetad(ic, &
&       jc, kc))/nablaeta(ic, jc, kc)
      shocknormaly(ic, kc) = temp2
      temp2 = detadz(ic, jc, kc)/nablaeta(ic, jc, kc)
      shocknormalzd(ic, kc) = (detadzd(ic, jc, kc)-temp2*nablaetad(ic, &
&       jc, kc))/nablaeta(ic, jc, kc)
      shocknormalz(ic, kc) = temp2
    END DO
  END DO
  
  call Parallel_Exchange_Surface(shocknormalx)
  call Parallel_Exchange_Surface(shocknormaly)
  call Parallel_Exchange_Surface(shocknormalz)
  call Parallel_Exchange_Surface(shocknormalxd)
  call Parallel_Exchange_Surface(shocknormalyd)
  call Parallel_Exchange_Surface(shocknormalzd)
  
! Standing for the Shock Surface
  jc = ny_local
  srhod = 0.0_8
  spd = 0.0_8
  std = 0.0_8
  sud = 0.0_8
  svd = 0.0_8
  swd = 0.0_8
  DO kc=1-overlap,nz_local+overlap
    DO ic=1-overlap,nx_local+overlap
!Velocity ahead of the shocks
      temp2 = wallnormalx(ic, kc)*shocknormalx(ic, kc) + wallnormaly(ic&
&       , kc)*shocknormaly(ic, kc) + wallnormalz(ic, kc)*shocknormalz(ic&
&       , kc)
      delta_infd = shocknormalx(ic, kc)*u_freed(ic, jc, kc) + u_free(ic&
&       , jc, kc)*shocknormalxd(ic, kc) + shocknormaly(ic, kc)*v_freed(&
&       ic, jc, kc) + v_free(ic, jc, kc)*shocknormalyd(ic, kc) + &
&       shocknormalz(ic, kc)*w_freed(ic, jc, kc) + w_free(ic, jc, kc)*&
&       shocknormalzd(ic, kc) - temp2*shockvd(ic, kc) - shockv(ic, kc)*(&
&       wallnormalx(ic, kc)*shocknormalxd(ic, kc)+wallnormaly(ic, kc)*&
&       shocknormalyd(ic, kc)+wallnormalz(ic, kc)*shocknormalzd(ic, kc))
      delta_inf = u_free(ic, jc, kc)*shocknormalx(ic, kc) + v_free(ic, &
&       jc, kc)*shocknormaly(ic, kc) + w_free(ic, jc, kc)*shocknormalz(&
&       ic, kc) - shockv(ic, kc)*temp2
      temp2 = (gamma+1.d0)*delta_inf*rho_free(ic, jc, kc)
      temp1 = p_free(ic, jc, kc)/temp2
      delta2d = (gamma-1.d0)*delta_infd/(gamma+1.d0) + gamma*2.d0*(&
&       p_freed(ic, jc, kc)-temp1*(rho_free(ic, jc, kc)*(gamma+1.d0)*&
&       delta_infd+(gamma+1.d0)*delta_inf*rho_freed(ic, jc, kc)))/temp2
      delta2 = (gamma-1.d0)*(delta_inf/(gamma+1.d0)) + gamma*2.d0*temp1
!Velocity normal to the shock after the shock
      sud(ic, jc, kc) = u_freed(ic, jc, kc) + shocknormalx(ic, kc)*(&
&       delta2d-delta_infd) + (delta2-delta_inf)*shocknormalxd(ic, kc)
      su(ic, jc, kc) = u_free(ic, jc, kc) + (delta2-delta_inf)*&
&       shocknormalx(ic, kc)
      svd(ic, jc, kc) = v_freed(ic, jc, kc) + shocknormaly(ic, kc)*(&
&       delta2d-delta_infd) + (delta2-delta_inf)*shocknormalyd(ic, kc)
      sv(ic, jc, kc) = v_free(ic, jc, kc) + (delta2-delta_inf)*&
&       shocknormaly(ic, kc)
      swd(ic, jc, kc) = w_freed(ic, jc, kc) + shocknormalz(ic, kc)*(&
&       delta2d-delta_infd) + (delta2-delta_inf)*shocknormalzd(ic, kc)
      sw(ic, jc, kc) = w_free(ic, jc, kc) + (delta2-delta_inf)*&
&       shocknormalz(ic, kc)
      temp2 = delta_inf*delta_inf/(gamma+1.0)
      spd(ic, jc, kc) = 2.0*(temp2*rho_freed(ic, jc, kc)+rho_free(ic, jc&
&       , kc)*2*delta_inf*delta_infd/(gamma+1.0)) - (gamma-1.0)*p_freed(&
&       ic, jc, kc)/(gamma+1.0)
      sp(ic, jc, kc) = 2.0*(rho_free(ic, jc, kc)*temp2) - (gamma-1.0)*(&
&       p_free(ic, jc, kc)/(gamma+1.0))
      temp2 = delta_inf/delta2
      srhod(ic, jc, kc) = temp2*rho_freed(ic, jc, kc) + rho_free(ic, jc&
&       , kc)*(delta_infd-temp2*delta2d)/delta2
      srho(ic, jc, kc) = rho_free(ic, jc, kc)*temp2
      temp2 = gamma*(mach_ref*mach_ref)
      temp1 = sp(ic, jc, kc)/srho(ic, jc, kc)
      std(ic, jc, kc) = temp2*(spd(ic, jc, kc)-temp1*srhod(ic, jc, kc))/&
&       srho(ic, jc, kc)
      st(ic, jc, kc) = temp2*temp1
    END DO
  END DO
  
  DEALLOCATE(x_grid)
  DEALLOCATE(y_grid)
  DEALLOCATE(z_grid)
  IF (ALLOCATED(shockhdxid)) THEN
    DEALLOCATE(shockhdxid)
  END IF
  DEALLOCATE(shockhdxi)
  IF (ALLOCATED(shockhdzetad)) THEN
    DEALLOCATE(shockhdzetad)
  END IF
  DEALLOCATE(shockhdzeta)
  IF (ALLOCATED(shockvdxid)) THEN
    DEALLOCATE(shockvdxid)
  END IF
  DEALLOCATE(shockvdxi)
  IF (ALLOCATED(shockvdzetad)) THEN
    DEALLOCATE(shockvdzetad)
  END IF
  DEALLOCATE(shockvdzeta)
  IF (ALLOCATED(dxdxid)) THEN
    DEALLOCATE(dxdxid)
  END IF
  DEALLOCATE(dxdxi)
  IF (ALLOCATED(dxdetad)) THEN
    DEALLOCATE(dxdetad)
  END IF
  DEALLOCATE(dxdeta)
  IF (ALLOCATED(dxdzetad)) THEN
    DEALLOCATE(dxdzetad)
  END IF
  DEALLOCATE(dxdzeta)
  IF (ALLOCATED(dydxid)) THEN
    DEALLOCATE(dydxid)
  END IF
  DEALLOCATE(dydxi)
  IF (ALLOCATED(dydetad)) THEN
    DEALLOCATE(dydetad)
  END IF
  DEALLOCATE(dydeta)
  IF (ALLOCATED(dydzetad)) THEN
    DEALLOCATE(dydzetad)
  END IF
  DEALLOCATE(dydzeta)
  IF (ALLOCATED(dzdxid)) THEN
    DEALLOCATE(dzdxid)
  END IF
  DEALLOCATE(dzdxi)
  IF (ALLOCATED(dzdetad)) THEN
    DEALLOCATE(dzdetad)
  END IF
  DEALLOCATE(dzdeta)
  IF (ALLOCATED(dzdzetad)) THEN
    DEALLOCATE(dzdzetad)
  END IF
  DEALLOCATE(dzdzeta)
  IF (ALLOCATED(jacod)) THEN
    DEALLOCATE(jacod)
  END IF
  DEALLOCATE(jaco)
  DEALLOCATE(invjacodt)
  DEALLOCATE(dxidx)
  DEALLOCATE(dxidy)
  DEALLOCATE(dxidz)
  IF (ALLOCATED(detadxd)) THEN
    DEALLOCATE(detadxd)
  END IF
  DEALLOCATE(detadx)
  IF (ALLOCATED(detadyd)) THEN
    DEALLOCATE(detadyd)
  END IF
  DEALLOCATE(detady)
  IF (ALLOCATED(detadzd)) THEN
    DEALLOCATE(detadzd)
  END IF
  DEALLOCATE(detadz)
  DEALLOCATE(dzetadx)
  DEALLOCATE(dzetady)
  DEALLOCATE(dzetadz)
  DEALLOCATE(nablaxi)
  IF (ALLOCATED(nablaetad)) THEN
    DEALLOCATE(nablaetad)
  END IF
  DEALLOCATE(nablaeta)
  DEALLOCATE(nablazeta)
  IF (ALLOCATED(shocknormalxd)) THEN
    DEALLOCATE(shocknormalxd)
  END IF
  DEALLOCATE(shocknormalx)
  IF (ALLOCATED(shocknormalyd)) THEN
    DEALLOCATE(shocknormalyd)
  END IF
  DEALLOCATE(shocknormaly)
  IF (ALLOCATED(shocknormalzd)) THEN
    DEALLOCATE(shocknormalzd)
  END IF
  DEALLOCATE(shocknormalz)
END SUBROUTINE LINEARIZED_SHOCKBC_D

!  Differentiation of calculate_fdxi_surf_ce_bc in forward (tangent) mode:
!   variations   of useful results: df
!   with respect to varying inputs: f
SUBROUTINE CALCULATE_FDXI_SURF_CE_D_un_BC(df, dfd, f, fd, nx, nz, overlap, npx, npx0)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: nx, nz, overlap, npx, npx0
  REAL*8, INTENT(IN) :: f(1-overlap:nx+overlap, 1-overlap:nz+overlap)
  REAL*8, INTENT(IN) :: fd(1-overlap:nx+overlap, 1-overlap:nz+overlap)
  REAL*8, INTENT(OUT) :: df(1-overlap:nx+overlap, 1-overlap:nz+overlap)
  REAL*8, INTENT(OUT) :: dfd(1-overlap:nx+overlap, 1-overlap:nz+overlap)
  INTEGER*4 :: ic, kc
  df = 0.d0
  dfd = 0.0_8
  DO kc=1,nz
    DO ic=1,nx
      dfd(ic, kc) = 9.d0*fd(ic-2, kc) - fd(ic-3, kc) - 45.d0*fd(ic-1, kc) + &
&       45.d0*fd(ic+1, kc) - 9.d0*fd(ic+2, kc) + fd(ic+3, kc)
      df(ic, kc) = -(1.d0*f(ic-3, kc)) + 9.d0*f(ic-2, kc) - 45.d0*f(ic-1, kc) + &
&       45.d0*f(ic+1, kc) - 9.d0*f(ic+2, kc) + f(ic+3, kc)
      dfd(ic, kc) = dfd(ic, kc)/60.d0
      df(ic, kc) = df(ic, kc)/60.d0
    END DO
  END DO
  if (npx == 0)then
  DO kc=1,nz
    ic = 1
    dfd(ic, kc) = (240*fd(ic+1, kc)-125.d0*fd(ic, kc)-180.d0*fd(ic+2, kc)+80.d0*&
&     fd(ic+3, kc)-15.d0*fd(ic+4, kc))/60.d0
    df(ic, kc) = (-(125.d0*f(ic, kc))+240*f(ic+1, kc)-180.d0*f(ic+2, kc)+80.d0*f&
&     (ic+3, kc)-15.d0*f(ic+4, kc))/60.d0
    ic = 2
    dfd(ic, kc) = (90.d0*fd(ic+1, kc)-50.d0*fd(ic, kc)-15.d0*fd(ic-1,kc)+5.d0*&
&     fd(ic+3, kc)-30.d0*fd(ic+2, kc))/60.d0
    df(ic, kc) = (-(15.d0*f(ic-1,kc))-50.d0*f(ic, kc)+90.d0*f(ic+1, kc)-30.d0*f&
&     (ic+2, kc)+5.d0*f(ic+3, kc))/60.d0
    ic = 3
    dfd(ic, kc) = (5.d0*fd(ic-2,kc)-40.d0*fd(ic-1,kc)+40.d0*fd(ic+1, kc)-5.d0*&
&     fd(ic+2, kc))/60.d0
    df(ic, kc) = (5.d0*f(ic-2,kc)-40.d0*f(ic-1,kc)+0.d0*f(ic, kc)+40.d0*f(ic+1&
&     , kc)-5.d0*f(ic+2, kc))/60.d0
  END DO
  END IF
  
  if (npx == npx0 - 1)then
  DO kc=1,nz
    ic = nx - 2
    dfd(ic, kc) = (40.d0*fd(ic+1, kc)-5.d0*fd(ic+2, kc)+5.d0*fd(ic-2,kc)-40.d0*&
&     fd(ic-1,kc))/60.d0
    df(ic, kc) = (-(5.d0*f(ic+2, kc))+40.d0*f(ic+1, kc)+0.d0*f(ic, kc)-40.d0*f(ic&
&     -1, kc)+5.d0*f(ic-2,kc))/60.d0
    ic = nx - 1
    dfd(ic, kc) = (15.d0*fd(ic+1, kc)+50.d0*fd(ic, kc)-90.d0*fd(ic-1,kc)+30.d0*&
&     fd(ic-2,kc)-5.d0*fd(ic-3, kc))/60.d0
    df(ic, kc) = (15.d0*f(ic+1, kc)+50.d0*f(ic, kc)-90.d0*f(ic-1,kc)+30.d0*f(ic-&
&     2, kc)-5.d0*f(ic-3, kc))/60.d0
    ic = nx
    dfd(ic, kc) = (125.d0*fd(ic, kc)-240.d0*fd(ic-1,kc)+180.d0*fd(ic-2,kc)+&
&     15.d0*fd(ic- 4, kc)-80.d0*fd(ic-3, kc))/60.d0
    df(ic, kc) = (125.d0*f(ic, kc)-240.d0*f(ic-1,kc)+180.d0*f(ic-2,kc)-80.d0*f&
&     (ic-3, kc)+15.d0*f(ic- 4, kc))/60.d0
  END DO
  END IF
END SUBROUTINE CALCULATE_FDXI_SURF_CE_D_un_BC

  !Differentiation of calculate_fdzeta_surf_ce in forward (tangent) mode:
  ! variations   of useful results: df
  ! with respect to varying inputs: f
SUBROUTINE CALCULATE_FDZETA_SURF_CE_D_un_BC(df, dfd, f, fd, nx, nz, overlap, npz, npz0)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: nx, nz, overlap, npz, npz0
  REAL*8, INTENT(IN) :: f(1-overlap:nx+overlap, 1-overlap:nz+overlap)
  REAL*8, INTENT(IN) :: fd(1-overlap:nx+overlap, 1-overlap:nz+overlap)
  REAL*8, INTENT(OUT) :: df(1-overlap:nx+overlap, 1-overlap:nz+overlap)
  REAL*8, INTENT(OUT) :: dfd(1-overlap:nx+overlap, 1-overlap:nz+overlap)
  INTEGER :: ic, kc
  df = 0.d0
  dfd = 0.0_8
  DO kc=1,nz
    DO ic=1,nx
      dfd(ic, kc) = 9.d0*fd(ic, kc-2) - fd(ic, kc-3) - 45.d0*fd(ic, kc-1) + &
&       45.d0*fd(ic, kc+1) - 9.d0*fd(ic, kc+2) + fd(ic, kc+3)
      df(ic, kc) = -(1.d0*f(ic, kc-3)) + 9.d0*f(ic, kc-2) - 45.d0*f(ic, kc-1) + &
&       45.d0*f(ic, kc+1) - 9.d0*f(ic, kc+2) + f(ic, kc+3)
      dfd(ic, kc) = dfd(ic, kc)/60.d0
      df(ic, kc) = df(ic, kc)/60.d0
    END DO
  END DO
  
  if (npz == 0)then
  DO ic=1,nx
    kc = 1
    dfd(ic, kc) = (240*fd(ic, kc+1)-125.d0*fd(ic, kc)-180.d0*fd(ic, kc+2)+80.d0*&
&     fd(ic, kc+3)-15.d0*fd(ic, kc+4))/60.d0
    df(ic, kc) = (-(125.d0*f(ic, kc))+240*f(ic, kc+1)-180.d0*f(ic, kc+2)+80.d0*f&
&     (ic, kc+3)-15.d0*f(ic, kc+4))/60.d0
    kc = 2
    dfd(ic, kc) = (90.d0*fd(ic, kc+1)-50.d0*fd(ic, kc)-15.d0*fd(ic, kc-1)+5.d0*&
&     fd(ic, kc+3)-30.d0*fd(ic, kc+2))/60.d0
    df(ic, kc) = (-(15.d0*f(ic, kc-1))-50.d0*f(ic, kc)+90.d0*f(ic, kc+1)-30.d0*f&
&     (ic, kc+2)+5.d0*f(ic, kc+3))/60.d0
    kc = 3
    dfd(ic, kc) = (5.d0*fd(ic, kc-2)-40.d0*fd(ic, kc-1)+40.d0*fd(ic, kc+1)-5.d0*&
&     fd(ic, kc+2))/60.d0
    df(ic, kc) = (5.d0*f(ic, kc-2)-40.d0*f(ic, kc-1)+0.d0*f(ic, kc)+40.d0*f(ic, kc&
&     +1)-5.d0*f(ic, kc+2))/60.d0
  END DO
  END IF
  
  if (npz == npz0 - 1)then
  DO ic=1,nx
    kc = nz - 2
    dfd(ic, kc) = (40.d0*fd(ic, kc+1)-5.d0*fd(ic, kc+2)+5.d0*fd(ic, kc-2)-40.d0*&
&     fd(ic, kc-1))/60.d0
    df(ic, kc) = (-(5.d0*f(ic, kc+2))+40.d0*f(ic, kc+1)+0.d0*f(ic, kc)-40.d0*f(ic&
&     , kc-1)+5.d0*f(ic, kc-2))/60.d0
    kc = nz - 1
    dfd(ic, kc) = (15.d0*fd(ic, kc+1)+50.d0*fd(ic, kc)-90.d0*fd(ic, kc-1)+30.d0*&
&     fd(ic, kc-2)-5.d0*fd(ic, kc-3))/60.d0
    df(ic, kc) = (15.d0*f(ic, kc+1)+50.d0*f(ic, kc)-90.d0*f(ic, kc-1)+30.d0*f(ic&
&     , kc-2)-5.d0*f(ic, kc-3))/60.d0
    kc = nz
    dfd(ic, kc) = (125.d0*fd(ic, kc)-240.d0*fd(ic, kc-1)+180.d0*fd(ic, kc-2)+&
&     15.d0*fd(ic, kc-4)-80.d0*fd(ic, kc-3))/60.d0
    df(ic, kc) = (125.d0*f(ic, kc)-240.d0*f(ic, kc-1)+180.d0*f(ic, kc-2)-80.d0*f&
&     (ic, kc-3)+15.d0*f(ic, kc-4))/60.d0
  END DO
  END IF
END SUBROUTINE CALCULATE_FDZETA_SURF_CE_D_un_BC
