subroutine Singular_Initial_Grid
  use SF_Constant,  only: ik,rk,pi,overLAP
  use SF_CFD_Global,only: Nx,nx_local,Ny,Nz,nz_local,Gamma,Geometry_Type,&
                          xim,ximax,sigma_y,yim,ymax,R_head,LModel,Nx_head,theta_p_rad,&
                          Mach_Normal,Nx_flate,Nx_head_hf,theta_p_deg
  use MPI_GLOBAL,   only: MyId,I_offset,K_offset,npx,npz
  ! arrays and matrixes
  use SF_CFD_Global,only: Heta,WallSX,WallSY,WallSZ,WallNormalX,WallNormalY,WallNormalZ,Sxi_Surface
  use SF_CFD_Global,only: HetaDeta,HetaDxi,HetaDzeta
  use SF_CFD_Global,only: WallSXdxi,WallSYdxi,WallSZdxi
  use SF_CFD_Global,only: WallSXdzeta,WallSYdzeta,WallSZdzeta
  use SF_CFD_Global,only: WallNormalXdxi,WallNormalYdxi,WallNormalZdxi
  use SF_CFD_Global,only: WallNormalXdzeta,WallNormalYdzeta,WallNormalZdzeta
  use SF_CFD_Global,only: ShockH,ShockV,X_grid,Y_grid,Z_grid,Lz_start,Lz_end
  use SF_CFD_Global,only: WallSX_total,WallSY_total,WallSZ_total,WallNormalX_total,WallNormalY_total,WallNormalZ_total,&
      &shockH_total,shockV_total,X_grid_total,Y_grid_total,Z_grid_total,WallSXdxi_total,WallSYdxi_total,WallSZdxi_total,&
      &WallSXdzeta_total,WallSYdzeta_total,WallSZdzeta_total,WallNormalXdxi_total,WallNormalYdxi_total,WallNormalZdxi_total,&
      &WallNormalXdzeta_total,WallNormalYdzeta_total,WallNormalZdzeta_total,Hetadxi_total,Hetadeta_total,Hetadzeta_total,Sxi_Surface_total
  ! subroutines
  use MPI_GLOBAL,     only: Parallel_Exchange,Parallel_Exchange_Surface
  use OutputParaView, only: output_initial_grid
  use FD5_Order,      only: Cal_Deri_SurfDxi_5th_ce,Cal_Deri_Deta_5th_ce,&
                           &Cal_Deri_Dxi_5th_ce,Cal_Deri_SurfDzeta_5th_ce,Cal_Deri_Dzeta_5th_ce_per!,Cal_Deri_Dzeta_5th_ce
    implicit none

    ! Local variables
           logical :: dir_exists
  INTEGER( kind=ik)::ic,jc,kc,ic_global,kc_global
  
  REAL( kind = rk )::S_head,S_flate,S_total
  REAL( kind = rk )::sxi_nxr
  ! Define some emperical Shock shape variables
  REAL( kind = rk )::delta, Rc, tan2,dxi
  ! Cluster coefficients along eta direction
  REAL( kind = rk )::eta_ay,eta_by,Ytemp,eta
  ! Coefficients along xi directions
  REAL( kind = rk )::szeta(1:Nz)
  REAL( kind = rk )::phi(1:Nz)
  REAL( kind = rk )::xi_ax,xi_bx,xi
  REAL( kind = rk )::sxi(1:2*Nx_head)
  REAL( kind = rk )::sxi0(1:Nx_head+1)
  REAL( kind = rk )::sxi_total(1:Nx_head)
  REAL( kind = rk )::theta_lcl
  REAL( kind = rk )::ds1,ds_uni,ds2
  
  REAL( kind = rk )::beta
  REAL( kind = rk )::GWallSX(1:Nx)
  REAL( kind = rk )::GWallSY(1:Nx)
  REAL( kind = rk )::GWallSZ(1:Nz)
  REAL( kind = rk )::GWallNormalX(1:Nx)
  REAL( kind = rk )::GWallNormalY(1:Nx)
  REAL( kind = rk )::GShockH(1:Nx)
  REAL( kind = rk )::GSxi_Surface(1:Nx)
  REAL( kind = rk )::shk_xgrid2,shk_ygrid2,temp
  REAL( kind = rk )::xx_flateplate(1:Nx_flate)
  character(len=8)  :: date 
  character(len=10) :: time
  real( kind = rk ), parameter :: a = 1.0d-3   ! 首项非零最小值（可调整，建议1e-3~1e-2）
  real( kind = rk ), parameter :: beta0 = 4.0d0  ! 曲率控制参数（可调整，建议2.0~8.0）

  ! Here we briefly describe the grid generation method
  ! This solver is used only for the grid in the x-y plane
  ! Then the grid in the z direction is generated by the duplication of the x-y plane
  ! The grid is generated by the following steps

  ! The geometry is defined by two parts, they first part is the rounded head part
  ! The second part is the flat plate part
  ! The grid is generated to have a blunt cone shape

  ! Define the streamwise sxi
  sxi          =  0.0_rk;
  sxi_total    =  0.0_rk;
  
  ! Global Wall Surface Coordinates (X,Y,Z)
  GWallSX      =  0.0_rk;
  GWallSY      =  0.0_rk;
  
  ! Global Wall Normal Vector (nwx,nwy,nwz)
  GWallNormalX =  0.0_rk;
  GWallNormalY =  0.0_rk;
  
  ! Global Shock-Wall Distance GShockH
  GShockH      =  0.0_rk;
  
  
  S_head     = R_head * (pi - 2.0_rk * theta_p_rad)/2.d0;
  
  S_flate    = (LModel - R_head*(1.0_rk - sin(theta_p_rad)))/cos(theta_p_rad);
  
  if(LModel <= R_head*(1.0_rk - sin(theta_p_rad))) then
    !write(*,*)"The model is too small, please check the input parameters"
    S_flate = 0.0_rk;
  endif

  S_total    = S_head + S_flate;

  sxi_nxr    = 0.5_rk * pi - theta_p_rad;  ! define the half head for the model

  ! For this wedge, we have
  !delta      = R_head * 0.386 * exp(4.67 / Mach_Normal / Mach_Normal);
  !  Rc       = R_head * 1.386 * exp(1.8/(Mach_Normal - 1.0)**0.75);  
  
  ! For this cone, we have
   delta      = R_head * 0.143 * exp(3.24 / Mach_Normal / Mach_Normal);
     Rc       = R_head * 1.143 * exp(0.54/(Mach_Normal - 1.0)**1.2);  
  
  ! define the Heta grid
   eta_ay    = ymax * yim / (ymax - 2.d0 * yim);
   eta_by    = 1.d0 + 2.d0 * eta_ay / ymax;

   DO jc = 1,Ny
        eta = -1.d0 + 2.d0 * (jc - 1.d0)/(Ny - 1.d0);   
      Ytemp = 2.d0 * ( (1.d0 - tanh(sigma_y)) * (eta + 1.d0)/2.d0)/&
                     ( 1.d0 - tanh( sigma_y * (eta + 1.d0)/2.d0) ) - 1.d0;
    Heta(:,jc,:)= eta_ay * (1.d0 + Ytemp)/(eta_by - Ytemp);
   ENDDO
  !
  ! define the xi grid
   
  dxi    = 2.d0/REAL(2*Nx_head - 1.d0);
  DO ic = 1,2*Nx_head
    sxi(ic) = -1.d0 + ( ic - 1.d0 )* dxi
  ENDDO
    sxi_total = sxi(Nx_head+1:2*Nx_head)
   
  !xi_ax      = ximax * xim / (ximax - 2.d0 * xim);
  !xi_bx      = 1.d0 + 2.d0 * xi_ax / ximax;
  !DO ic = 1,Nx_head
  !  xi = -1.d0 + 2.d0 * (ic - 1.d0)/(Nx_head - 1.d0);
  !  !sxi(ic) = (xi + 1.d0) / 2.d0;
  !  sxi(ic) = xi_ax * ( 1.d0 + xi )/( xi_bx - xi );
  !ENDDO
  !  sxi_total = sxi(1:Nx_head)
  !  sxi_total(1) = sxi_total(2)/4.d0
   
  !write(*,*)sxi_total
! define the szeta grid
  DO kc = 1,Nz
    szeta(kc) = (kc - 1.d0)/(Nz - 0.d0 );
      phi(kc) =  szeta(kc) * 2 * pi;
  enddo
  
  !% the first part
  DO ic = 1,Nx_head
    theta_lcl = sxi_total(ic) * sxi_nxr; 
    GSxi_Surface(ic) = theta_lcl;
    GWallSX(ic) = R_head * (1.d0 - cos(theta_lcl));
    GWallSY(ic) = R_head * sin(theta_lcl);
    GWallNormalX(ic) = -cos(theta_lcl);
    GWallNormalY(ic) = sin(theta_lcl);
  ENDDO

  if( S_flate > 0.d0 ) then
    ! start ds1
    ds1 = R_head * (sxi_total(Nx_head) * sxi_nxr - sxi_total(Nx_head-1) * sxi_nxr);
   
    ds_uni = S_flate / (Nx_flate - 1.d0);
  
    ds2 = max(3*ds1,3*ds_uni);
  
    call SettingTransformation(xx_flateplate,S_flate,Nx_flate,ds1,ds2)
    
 !write(*,*)xx_flateplate  
    ! the second part
  
    Do ic = Nx_head+1,Nx
     GSxi_Surface(ic) = GSxi_Surface(ic-1) + sxi_nxr / (2.d0 * Nx);
     GWallSX(ic) = GWallSX(Nx_head) + xx_flateplate(ic + 1 - Nx_head) * cos(theta_p_rad);
     GWallSY(ic) = GWallSY(Nx_head) + xx_flateplate(ic + 1 - Nx_head) * sin(theta_p_rad);
     GWallNormalX(ic) = -sin(theta_p_rad);
     GWallNormalY(ic) =  cos(theta_p_rad);
    enddo

  endif

  ! define the Shock angle
  call Calculate_ShockTheta(beta,theta_p_rad,Mach_Normal,Gamma)
  
  tan2 = tan(beta) * tan(beta);
  ! 
if( theta_p_deg >= 0.5_rk) then
   ! the flate part is not horizontal
   do ic = 1,Nx
       !do kc = 1,Nz
         !if (kc < Nz/2 + 1) then
           call Calculate_ShockHeight(GShockH(ic),&
           GWallSX(ic), GWallSY(ic), GWallNormalX(ic), GWallNormalY(ic),delta, Rc, tan2)
         !else
         !  call Calculate_ShockHeight(GShockH(ic),&
         !  GWallSX(ic), -GWallSY(ic), GWallNormalX(ic), -GWallNormalY(ic),delta, Rc, tan2)      
         !endif
         
       !enddo
   enddo
else

   
    If (Geometry_Type == 1)then
       ic = 1
      temp = R_head*R_head*tan2 &
           + 2.d0 * R_head * delta * tan2 &
           + delta * delta * tan2 &
           + 2.d0 * R_head * Rc &
           + 2.d0 * Rc * delta;
    shk_xgrid2  =  R_head;  
    shk_ygrid2  = -sqrt(temp);
    GShockH(ic) = sqrt((shk_xgrid2 - GWallSX(ic))**2.d0+(shk_ygrid2 - GWallSY(ic))**2.d0);
             
   do ic = 2,Nx_head-1
     call Calculate_ShockHeight(GShockH(ic),&
       GWallSX(ic), GWallSY(ic), GWallNormalX(ic), GWallNormalY(ic),delta, Rc, tan2)     
   enddo
  
  
   do ic = Nx_head,Nx
     temp = GWallSX(ic)*GWallSX(ic)*tan2  &  
          + 2.d0 * GWallSX(ic) * delta * tan2  & 
          + delta * delta * tan2   &
          + 2.d0 * GWallSX(ic) * Rc  &
          + 2.d0 * Rc * delta;
     shk_ygrid2 =  sqrt(temp);
     shk_xgrid2 =  GWallSX(ic);
    GShockH(ic) = sqrt((shk_xgrid2 - GWallSX(ic))**2.d0+(shk_ygrid2 - GWallSY(ic))**2.d0); 
   enddo
   
   
   
  elseif (Geometry_Type == 2)then
       do ic = 1,Nx_head
             call Calculate_ShockHeight(GShockH(ic),&
             GWallSX(ic), GWallSY(ic), GWallNormalX(ic), GWallNormalY(ic),delta, Rc, tan2)     
     enddo
  endif
  
  endif 

   
  !if(MyId == 0) then
  ! write(*,*)"The main node output surface Coordinates"
  ! !Check Points: Output WallSX and WallSY
  ! inquire(file="CheckFiles", exist=dir_exists)
  ! if (.not. dir_exists) then
  !   call system("mkdir -p CheckFiles")
  ! endif
  ! open(123,file="CheckFiles/SurfaceCoordinate.dat",status="replace")
  ! write(123,*)"VARIABLES=ic, WallSX, WallSY, ShockH, GSxi"
  !  do ic = 1,Nx
  !   write(123,*)ic,GWallSX(ic),GWallSY(ic),GShockH(ic),GSxi_Surface(ic)
  !  enddo 
  ! close(123) 
  !endif
  
  ! Setting the grid points along I,K direction
  do kc = 1,nz_local
   kc_global = K_offset(npz) + kc - 1

   do ic = 1,nx_local
             ic_global = I_offset(npx) + ic - 1
         WallSX(ic,kc) = GWallSX(ic_global);                           ! Surface X grid
         WallSY(ic,kc) = GWallSY(ic_global)*cos(phi(kc_global));       ! Surface Y grid
         WallSZ(ic,kc) = GWallSY(ic_global)*sin(phi(kc_global));       ! Surface Z grid
    WallNormalX(ic,kc) = GWallNormalX(ic_global);                      ! Surface wallnormal vector X
    WallNormalY(ic,kc) = GWallNormalY(ic_global)*cos(phi(kc_global));  ! Surface wallnormal vector Y
    WallNormalZ(ic,kc) = GWallNormalY(ic_global)*sin(phi(kc_global));  ! Surface wallnormal vector Z
         ShockH(ic,: ) = GShockH(ic_global);                           ! Shock Height
    Sxi_Surface(ic,: ) = GSxi_Surface(ic_global);                      ! Sxi surface
   ENDDO

  ENDDO
  
  !write(*,*),'WallSX(1,1)',npx,npz,WallSX(1,1)
  !write(*,*),'WallSX(2,2)',npx,npz,WallSX(2,2)
  !write(*,*),'WallSX(3,3)',npx,npz,WallSX(3,3)
  !    
  !write(*,*),npx,npz,WallSX(0,1)
  !write(*,*),npx,npz,WallSX(-1,2)
  !write(*,*),npx,npz,WallSX(-2,3)
  !write(*,*),npx,npz,WallSX_total(1,21)
  !write(*,*),npx,npz,WallSX_total(2,22)
  !write(*,*),npx,npz,WallSX_total(3,23)
  !call DATE_AND_TIME(date, time)
  !WRITE(*,*) 'before', MyId+1, time
  CALL Parallel_Exchange_singularity_surface(WallSX,WallSX_total)
  !call DATE_AND_TIME(date, time)
  !WRITE(*,*) 'after', MyId+1, time  
  !pause
  
  CALL Parallel_Exchange_singularity_surface(WallSY,WallSY_total)
  CALL Parallel_Exchange_singularity_surface(WallSZ,WallSZ_total)
  CALL Parallel_Exchange_singularity_surface(WallNormalX,WallNormalX_total)
  CALL Parallel_Exchange_singularity_surface(WallNormalY,WallNormalY_total)
  CALL Parallel_Exchange_singularity_surface(WallNormalZ,WallNormalZ_total)
  CALL Parallel_Exchange_singularity_surface(ShockH,shockH_total)
  CALL Parallel_Exchange_singularity_surface(Sxi_Surface,Sxi_Surface_total)
  
  
  

  !write(*,*),'WallSX(:,20)',WallSX(-1,:)
  !write(*,*),'after exchange',npx,npz,WallSX(0,1)
  !write(*,*),'after exchange',npx,npz,WallSX(-1,2)
  !write(*,*),'after exchange',npx,npz,WallSX(-2,3)
  !write(*,*),'after exchange',npx,npz,WallSX_total(1,21)
  !write(*,*),'after exchange',npx,npz,WallSX_total(2,22)
  !write(*,*),'after exchange',npx,npz,WallSX_total(3,23)
  !!!!
  !pause
  
  !write(*,*)"WallSX_total"
  !write(*,*),'WallSX(:,1)',WallSX(:,1)
  !write(*,*),'WallSX_total(:,1)',WallSX_total(:,1)
  !pause
  
  Call Parallel_Exchange_Surface(WallSX)
  Call Parallel_Exchange_Surface(WallSY)
  Call Parallel_Exchange_Surface(WallSZ)
  Call Parallel_Exchange_Surface(WallNormalX)
  Call Parallel_Exchange_Surface(WallNormalY)
  Call Parallel_Exchange_Surface(WallNormalZ)
  Call Parallel_Exchange_Surface(ShockH)
  Call Parallel_Exchange_Surface(Sxi_Surface) 
  
  ! The initial shock velocity is set to zero
  ShockV = 0.0_rk;

  ! generate the grid points on local domain for X , Y and Z directions 3D
  DO kc = 1-overLAP,nz_local+overLAP
   DO jc = 1,Ny
    DO ic = 1-overLAP,nx_local+overLAP
      X_grid(ic,jc,kc) = WallSX(ic,kc) + WallNormalX(ic,kc) * ShockH(ic,kc) * Heta(ic,jc,kc);
      Y_grid(ic,jc,kc) = WallSY(ic,kc) + WallNormalY(ic,kc) * ShockH(ic,kc) * Heta(ic,jc,kc);
      Z_grid(ic,jc,kc) = WallSZ(ic,kc) + WallNormalZ(ic,kc) * ShockH(ic,kc) * Heta(ic,jc,kc);
    ENDDO
   ENDDO
  ENDDO

  !if (Myid == 0)then


  

  !!endif 
  
  call Parallel_Exchange_singularity(X_grid,X_grid_total)
  call Parallel_Exchange_singularity(Y_grid,Y_grid_total)
  call Parallel_Exchange_singularity(Z_grid,Z_grid_total)
  
  call Parallel_Exchange(X_grid)
  call Parallel_Exchange(Y_grid)
  call Parallel_Exchange(Z_grid)
  
  !write(*,*),'X_grid(-2:3,Ny,1)',X_grid(-2:3,Ny,1)
  !write(*,*),'Y_grid(-2:3,Ny,1)',Y_grid(-2:3,Ny,1)
  !write(*,*),'Z_grid(-2:3,Ny,1)',Z_grid(-2:3,Ny,1)
  !
  !pause
  
  if(MyId == 0) then
   write(*,*)"Output the initial grid" 
  endif

  call output_initial_grid

  if(MyId == 0) then
   write(*,*)"Output the initial grid finished" 
  endif

  ! Here we need to calculate some derivatives 
  ! with respect to the Wall Surface variables
   
  ! only the xi direction need parallel exchange
  
   CALL Cal_Deri_SurfDxi_5th_ce(WallSXdxi,WallSX)
   CALL Cal_Deri_SurfDxi_5th_ce(WallSYdxi,WallSY)
   CALL Cal_Deri_SurfDxi_5th_ce(WallSZdxi,WallSZ)
   CALL Cal_Deri_SurfDzeta_5th_ce(WallSXdzeta,WallSX)
   CALL Cal_Deri_SurfDzeta_5th_ce(WallSYdzeta,WallSY)
   CALL Cal_Deri_SurfDzeta_5th_ce(WallSZdzeta,WallSZ)
    
  !write(*,*),'WallSXdxi(1,1)',WallSXdxi(0,1)
  !write(*,*),'WallSXdxi(1,2)',WallSXdxi(-1,2)
  !write(*,*),'WallSXdxi(1,3)',WallSXdxi(-2,3)
  !write(*,*),'WallSXdxi_total(1,21)',WallSXdxi_total(1,21)
  !write(*,*),'WallSXdxi_total(1,22)',WallSXdxi_total(2,22)
  !write(*,*),'WallSXdxi_total(1,23)',WallSXdxi_total(3,23)
     
  !write(*,*),'WallSXdxi(1,1)',WallSXdxi(0,1)
  !write(*,*),'WallSXdxi(1,2)',WallSXdxi(-1,2)
  !write(*,*),'WallSXdxi(1,3)',WallSXdxi(-2,3)
  !write(*,*),'WallSXdxi_total(1,21)',WallSXdxi_total(1,21)
  !write(*,*),'WallSXdxi_total(1,22)',WallSXdxi_total(2,22)
  !write(*,*),'WallSXdxi_total(1,23)',WallSXdxi_total(3,23)
  !PAUSE
   
   
   call Parallel_Exchange_singularity_surface_negative(WallSXdxi,WallSXdxi_total)
   call Parallel_Exchange_singularity_surface_negative(WallSYdxi,WallSYdxi_total)
   call Parallel_Exchange_singularity_surface_negative(WallSZdxi,WallSZdxi_total)
   call Parallel_Exchange_singularity_surface(WallSXdzeta,WallSXdzeta_total)
   call Parallel_Exchange_singularity_surface(WallSYdzeta,WallSYdzeta_total)
   call Parallel_Exchange_singularity_surface(WallSZdzeta,WallSZdzeta_total)
   
   
   CALL Parallel_Exchange_Surface(WallSXdxi)
   CALL Parallel_Exchange_Surface(WallSYdxi)
   CALL Parallel_Exchange_Surface(WallSZdxi)
   CALL Parallel_Exchange_Surface(WallSXdzeta)
   CALL Parallel_Exchange_Surface(WallSYdzeta)
   CALL Parallel_Exchange_Surface(WallSZdzeta)  
   
   
   CALL Cal_Deri_SurfDxi_5th_ce(WallNormalXdxi,WallNormalX)
   CALL Cal_Deri_SurfDxi_5th_ce(WallNormalYdxi,WallNormalY)
   CALL Cal_Deri_SurfDxi_5th_ce(WallNormalZdxi,WallNormalZ)
   CALL Cal_Deri_SurfDzeta_5th_ce(WallNormalXdzeta,WallNormalX)
   CALL Cal_Deri_SurfDzeta_5th_ce(WallNormalYdzeta,WallNormalY)
   CALL Cal_Deri_SurfDzeta_5th_ce(WallNormalZdzeta,WallNormalZ)  
    
   CALL Parallel_Exchange_singularity_surface_negative(WallNormalXdxi,WallNormalXdxi_total)
   CALL Parallel_Exchange_singularity_surface_negative(WallNormalYdxi,WallNormalYdxi_total)
   CALL Parallel_Exchange_singularity_surface_negative(WallNormalZdxi,WallNormalZdxi_total)
   CALL Parallel_Exchange_singularity_surface(WallNormalXdzeta,WallNormalXdzeta_total)
   CALL Parallel_Exchange_singularity_surface(WallNormalYdzeta,WallNormalYdzeta_total)
   CALL Parallel_Exchange_singularity_surface(WallNormalZdzeta,WallNormalZdzeta_total)
   
   
   CALL Parallel_Exchange_Surface(WallNormalXdxi)
   CALL Parallel_Exchange_Surface(WallNormalYdxi)
   CALL Parallel_Exchange_Surface(WallNormalZdxi)
   CALL Parallel_Exchange_Surface(WallNormalXdzeta)
   CALL Parallel_Exchange_Surface(WallNormalYdzeta)
   CALL Parallel_Exchange_Surface(WallNormalZdzeta)

   
   !CALL Parallel_Exchange_singularity(Heta)   
   CALL Parallel_Exchange(Heta)   
   
   CALL Cal_Deri_Dxi_5th_ce(HetaDxi,Heta)
   CALL Cal_Deri_Deta_5th_ce(Hetadeta,Heta) 
   CALL Cal_Deri_Dzeta_5th_ce_per(HetaDzeta,Heta)
    
   CALL Parallel_Exchange_singularity(HetaDxi,HetaDxi_total)
   CALL Parallel_Exchange_singularity(Hetadeta,HetaDeta_total)
   CALL Parallel_Exchange_singularity(HetaDzeta,HetaDzeta_total)
   
   CALL Parallel_Exchange(HetaDxi)
   CALL Parallel_Exchange(Hetadeta)
   CALL Parallel_Exchange(HetaDzeta)
   
   !pause
  ! Output some files for checking
  !if(MyId == 0) then
  ! write(*,*)"The main node output surface Coordinates derivatives"
  ! !Check Points: Output WallSX and WallSY
  ! open(123,file="CheckFiles/SurfaceCoordinateDiff.dat",status="replace")
  ! write(123,"(A)")"VARIABLES=WallSX,WallSXdxi,WallSY,WallSYdxi,WallSZ,&
  !                 & WallNormalX,WallNormalY,WallNormalXdxi,WallNormalYdxi"
  ! close(123)
  !
  ! open(123,file="CheckFiles/WallNormal.dat",status="replace")
  ! write(123,"(A)")"VARIABLES=jc,Heta,Hetadeta"
  ! close(123)
  !endif   
  
  end subroutine Singular_Initial_Grid
    
  SUBROUTINE Calculate_ShockHeight(shk_Height,WallSX, WallSY, WallNormalX, WallNormalY,delta, Rc, tan2)
  use SF_Constant,  only:rk
  implicit none
  real( kind = rk ) :: WallSX, WallSY, WallNormalX, WallNormalY
  real( kind = rk ) :: delta, Rc, tan2
  real( kind = rk ) :: shk_Height
  real( kind = rk ) :: a,b,c,tempY1
  real( kind = rk ) :: shk_ygrid2,shk_xgrid2

   a = WallNormalX * WallNormalX * tan2 - WallNormalY * WallNormalY;
   b =   2.d0 * delta * WallNormalX * WallNormalX * tan2 &
       + 2.d0 * Rc * WallNormalX * WallNormalX &
       - 2.d0 * WallNormalX * WallNormalY * WallSY &
       + 2.d0 * WallNormalY * WallNormalY * WallSX;
   c = delta * delta * tan2 * WallNormalX * WallNormalX &
       + 2.d0 * Rc * delta * WallNormalX * WallNormalX &
       - WallNormalX * WallNormalX * WallSY * WallSY &
       + 2.d0 * WallNormalX * WallNormalY * WallSX * WallSY &
       - WallNormalY * WallNormalY * WallSX * WallSX;
 
    tempY1 = (-b + sqrt(b*b - 4.d0 * a * c))/(2.d0 * a);
 
   shk_ygrid2 = WallSY + WallNormalY / WallNormalX * tempY1 - WallSX * WallNormalY/WallNormalX;
   shk_xgrid2 = Rc/tan2 * (sqrt(1.d0 + shk_ygrid2 * shk_ygrid2 * tan2/(Rc * Rc)) - 1.d0) - delta;
   shk_Height = sqrt((shk_xgrid2 - WallSX)**2.d0+(shk_ygrid2 - WallSY)**2.d0);

END SUBROUTINE Calculate_ShockHeight

! This subroutine calculate the grid distribution for a smooth transformation
SUBROUTINE SettingTransformation(XX,Length,Nx,dx1,dx2)
  ! This subroutine calculate a smooth distributions
  ! 
  use SF_Constant,    only:ik,rk
  implicit none
  integer( kind = ik )::Nx
  real( kind = rk ):: Length,dx1,dx2
  real( kind = rk ):: XX(1:Nx)

  real( kind = rk )::xuniform,Ah1,Sh0,Sh1
  integer(kind=ik ):: ic

  DO ic = 1,Nx
    xuniform = ( ic - 1.d0 )/( Nx - 1.d0 );
    Ah1 = ( 1.d0 - 2.d0 * ( xuniform - 1.d0 )) * xuniform * xuniform;
    Sh0 = xuniform * (xuniform - 1.d0)**2;
    Sh1 = (xuniform - 1.d0) * xuniform * xuniform;
    XX(ic) = Length * Ah1 + dx1 * (Nx - 1.d0) * Sh0 + dx2 * (Nx - 1.d0) * Sh1;
  ENDDO

END SUBROUTINE SettingTransformation

! This subroutine calculate the local shock angle 2D
SUBROUTINE Calculate_ShockTheta(beta,theta_p_rad,Mach_n,Gamma)
   use SF_Constant, only:rk
   implicit none
   real(kind = rk)::beta,theta_p_rad,Mach_n,Gamma
   real(kind = rk)::F,FP,FM,DFDB,EPS
   real(kind = rk)::Dbeta,TINY,FunMyCase

   beta = max(tan(theta_p_rad),2.0e-8_rk);
   Dbeta = 1.e-8;
   TINY = 1.0e-14;
   EPS = 1.d0;   
   do while(eps > tiny)
      F  = FunMyCase(beta,Mach_n,Gamma) - tan(theta_p_rad);
      FP = FunMyCase(beta+Dbeta,Mach_n,Gamma);
      FM = FunMyCase(beta-Dbeta,Mach_n,Gamma);
    DFDB = (FP - FM) / (2.0 * Dbeta);
     EPS = abs(F / DFDB);
    beta = beta - F / DFDB;      
   enddo

END SUBROUTINE Calculate_ShockTheta

function FunMyCase(beta,Ma,Gamma)
  use SF_Constant,    only:rk
  implicit none
  real( kind = rk )::FunMyCase,beta,Ma,Gamma
  real( kind = rk )::FuncCase1,FuncCase2
      FuncCase1 = Ma*Ma*sin(beta)*sin(beta) - 1.d0;
      FuncCase2 = Ma*Ma*(Gamma + cos(2*beta)) + 2.d0;
      FunMyCase = 2/tan(beta) * FuncCase1 / FuncCase2;
    end function
    
!subroutine Elliptical_Initial_Grid
!  use SF_Constant,  only: ik,rk,pi,overLAP
!  use SF_CFD_Global,only: Nx,nx_local,Ny,Nz,nz_local,Gamma,Geometry_Type,&
!                          xim,ximax,sigma_y,yim,ymax,R_head,LModel,Nx_head,theta_p_rad,&
!                          Mach_Normal,Nx_flate,Nx_head_hf,theta_p_deg
!  use MPI_GLOBAL,   only: MyId,I_offset,K_offset,npx,npz
!  ! arrays and matrixes
!  use SF_CFD_Global,only: Heta,WallSX,WallSY,WallSZ,WallNormalX,WallNormalY,WallNormalZ,Sxi_Surface
!  use SF_CFD_Global,only: HetaDeta,HetaDxi,HetaDzeta
!  use SF_CFD_Global,only: WallSXdxi,WallSYdxi,WallSZdxi
!  use SF_CFD_Global,only: WallSXdzeta,WallSYdzeta,WallSZdzeta
!  use SF_CFD_Global,only: WallNormalXdxi,WallNormalYdxi,WallNormalZdxi
!  use SF_CFD_Global,only: WallNormalXdzeta,WallNormalYdzeta,WallNormalZdzeta
!  use SF_CFD_Global,only: ShockH,ShockV,X_grid,Y_grid,Z_grid,Lz_start,Lz_end
!  use SF_CFD_Global,only: WallSX_total,WallSY_total,WallSZ_total,WallNormalX_total,WallNormalY_total,WallNormalZ_total,&
!      &shockH_total,shockV_total,X_grid_total,Y_grid_total,Z_grid_total,WallSXdxi_total,WallSYdxi_total,WallSZdxi_total,&
!      &WallSXdzeta_total,WallSYdzeta_total,WallSZdzeta_total,WallNormalXdxi_total,WallNormalYdxi_total,WallNormalZdxi_total,&
!      &WallNormalXdzeta_total,WallNormalYdzeta_total,WallNormalZdzeta_total,Hetadxi_total,Hetadeta_total,Hetadzeta_total,Sxi_Surface_total
!  ! subroutines
!  use MPI_GLOBAL,     only: Parallel_Exchange,Parallel_Exchange_Surface
!  use OutputParaView, only: output_initial_grid
!  use FD5_Order,      only: Cal_Deri_SurfDxi_5th_ce,Cal_Deri_Deta_5th_ce,&
!                           &Cal_Deri_Dxi_5th_ce,Cal_Deri_SurfDzeta_5th_ce,Cal_Deri_Dzeta_5th_ce_per!,Cal_Deri_Dzeta_5th_ce
!    implicit none
!
!    ! Local variables
!           logical :: dir_exists
!  INTEGER( kind=ik)::ic,jc,kc,ic_global,kc_global
!  
!  REAL( kind = rk )::S_head,S_flate,S_total
!  REAL( kind = rk )::sxi_nxr
!  ! Define some emperical Shock shape variables
!  REAL( kind = rk )::delta, Rc, tan2,dxi
!  ! Cluster coefficients along eta direction
!  REAL( kind = rk )::eta_ay,eta_by,Ytemp,eta
!  ! Coefficients along xi directions
!  REAL( kind = rk )::szeta(1:Nz)
!  REAL( kind = rk )::phi(1:Nz)
!  REAL( kind = rk )::xi_ax,xi_bx,xi
!  REAL( kind = rk )::sxi(1:2*Nx_head)
!  REAL( kind = rk )::sxi0(1:Nx_head+1)
!  REAL( kind = rk )::sxi_total(1:Nx_head)
!  REAL( kind = rk )::theta_lcl
!  REAL( kind = rk )::ds1,ds_uni,ds2
!  
!  REAL( kind = rk )::beta
!  REAL( kind = rk )::GWallSX(1:Nx)
!  REAL( kind = rk )::GWallSY(1:Nx)
!  REAL( kind = rk )::GWallSZ(1:Nz)
!  REAL( kind = rk )::GWallNormalX(1:Nx)
!  REAL( kind = rk )::GWallNormalY(1:Nx)
!  REAL( kind = rk )::GShockH(1:Nx)
!  REAL( kind = rk )::GSxi_Surface(1:Nx)
!  REAL( kind = rk )::shk_xgrid2,shk_ygrid2,temp
!  REAL( kind = rk )::xx_flateplate(1:Nx_flate)
!  character(len=8)  :: date 
!  character(len=10) :: time
!  real( kind = rk ), parameter :: a = 1.0d-3   ! 首项非零最小值（可调整，建议1e-3~1e-2）
!  real( kind = rk ), parameter :: beta0 = 4.d0  ! 曲率控制参数（可调整，建议2.0~8.0）
!  real( kind = rk ) :: scaled_xi, exp_term 
!  real( kind = rk ), parameter :: aspect_ratio = 2.d0
!  real( kind = rk ) :: norm_x,norm_y,norm_z,norm_val,temp_y,temp_z
!  real( kind = rk ) :: cos_phi,sin_phi,R_phi,R_circular,curvature_ratio,shock_height_factor
!  ! Here we briefly describe the grid generation method
!  ! This solver is used only for the grid in the x-y plane
!  ! Then the grid in the z direction is generated by the duplication of the x-y plane
!  ! The grid is generated by the following steps
!
!  ! The geometry is defined by two parts, they first part is the rounded head part
!  ! The second part is the flat plate part
!  ! The grid is generated to have a blunt cone shape
!
!  ! Define the streamwise sxi
!  sxi          =  0.0_rk;
!  sxi_total    =  0.0_rk;
!  
!  ! Global Wall Surface Coordinates (X,Y,Z)
!  GWallSX      =  0.0_rk;
!  GWallSY      =  0.0_rk;
!  
!  ! Global Wall Normal Vector (nwx,nwy,nwz)
!  GWallNormalX =  0.0_rk;
!  GWallNormalY =  0.0_rk;
!  
!  ! Global Shock-Wall Distance GShockH
!  GShockH      =  0.0_rk;
!  
!  
!  S_head     = R_head * (pi - 2.0_rk * theta_p_rad)/2.d0;
!  
!  S_flate    = (LModel - R_head*(1.0_rk - sin(theta_p_rad)))/cos(theta_p_rad);
!  
!  if(LModel <= R_head*(1.0_rk - sin(theta_p_rad))) then
!    !write(*,*)"The model is too small, please check the input parameters"
!    S_flate = 0.0_rk;
!  endif
!
!  S_total    = S_head + S_flate;
!
!  sxi_nxr    = 0.5_rk * pi - theta_p_rad;  ! define the half head for the model
!
!  ! For this wedge, we have
!  !delta      = R_head * 0.386 * exp(4.67 / Mach_Normal / Mach_Normal);
!  !  Rc       = R_head * 1.386 * exp(1.8/(Mach_Normal - 1.0)**0.75);  
!  
!  ! For this cone, we have
!   delta      = R_head * 0.143 * exp(3.24 / Mach_Normal / Mach_Normal);
!     Rc       = R_head * 1.143 * exp(0.54/(Mach_Normal - 1.0)**1.2);  
!  
!  ! define the Heta grid
!   eta_ay    = ymax * yim / (ymax - 2.d0 * yim);
!   eta_by    = 1.d0 + 2.d0 * eta_ay / ymax;
!
!   DO jc = 1,Ny
!        eta = -1.d0 + 2.d0 * (jc - 1.d0)/(Ny - 1.d0);   
!      Ytemp = 2.d0 * ( (1.d0 - tanh(sigma_y)) * (eta + 1.d0)/2.d0)/&
!                     ( 1.d0 - tanh( sigma_y * (eta + 1.d0)/2.d0) ) - 1.d0;
!    Heta(:,jc,:)= eta_ay * (1.d0 + Ytemp)/(eta_by - Ytemp);
!   ENDDO
!  !
!  ! define the xi grid
!   
!  dxi    = 2.d0/REAL(2*Nx_head - 1.d0);
!  DO ic = 1,2*Nx_head
!    sxi(ic) = -1.d0 + ( ic - 1.d0 )* dxi
!  ENDDO
!    sxi_total = sxi(Nx_head+1:2*Nx_head)
!   
!  !xi_ax      = ximax * xim / (ximax - 2.d0 * xim);
!  !xi_bx      = 1.d0 + 2.d0 * xi_ax / ximax;
!  !DO ic = 1,Nx_head
!  !  xi = -1.d0 + 2.d0 * (ic - 1.d0)/(Nx_head - 1.d0);
!  !  !sxi(ic) = (xi + 1.d0) / 2.d0;
!  !  sxi(ic) = xi_ax * ( 1.d0 + xi )/( xi_bx - xi );
!  !ENDDO
!  !  sxi_total = sxi(1:Nx_head)
!  !  sxi_total(1) = sxi_total(2)/4.d0
!   
!  !write(*,*)sxi_total
!! define the szeta grid
!  DO kc = 1,Nz
!    szeta(kc) = (kc - 1.d0)/(Nz - 0.d0 );
!      phi(kc) =  szeta(kc) * 2 * pi;
!  enddo
!  
!  !% the first part
!  !==============================================================================|
!  !                                                                              |
!  !                      Blunt Round 2D                                          |
!  !                                                                              |
!  !==============================================================================|
!  
!  DO ic = 1,Nx_head
!    theta_lcl = sxi_total(ic) * sxi_nxr; 
!    GSxi_Surface(ic) = theta_lcl;
!    GWallSX(ic) = R_head * (1.d0 - cos(theta_lcl));
!    GWallSY(ic) = R_head * sin(theta_lcl);
!    GWallNormalX(ic) = -cos(theta_lcl);
!    GWallNormalY(ic) =  sin(theta_lcl);
!  ENDDO 
!!!===========================================================================================|
!!!                                                                                           |
!!!                  Blunt Parabola 2D  （x = 1/(2*R) * y^2）                                 |
!!!                                                                                           |
!!!==========================================================================================!|
!  
!  !DO ic = 1,Nx_head
!  !  theta_lcl = sxi_total(ic) * sxi_nxr; 
!  !  GSxi_Surface(ic) = theta_lcl;
!  !  
!  !  GWallSY(ic) = sxi_total(ic) * 2 * R_head; 
!  !  GWallSX(ic) = 1.d0/(2 * R_head) * (GWallSY(ic))**2;
!  !  
!  !  GWallNormalX(ic) = -1.d0 / sqrt((GWallSY(ic)/R_head)**2+1.d0);
!  !  GWallNormalY(ic) = GWallSY(ic)/R_head/sqrt((GWallSY(ic)/R_head)**2+1.d0);
!  !  
!  !ENDDO
!  
!  if( S_flate > 0.d0 ) then
!    ! start ds1
!    ds1 = R_head * (sxi_total(Nx_head) * sxi_nxr - sxi_total(Nx_head-1) * sxi_nxr);
!   
!    ds_uni = S_flate / (Nx_flate - 1.d0);
!  
!    ds2 = max(3*ds1,3*ds_uni);
!  
!    call SettingTransformation(xx_flateplate,S_flate,Nx_flate,ds1,ds2)
!    
!    ! the second part
!  
!    Do ic = Nx_head+1,Nx
!     GSxi_Surface(ic) = GSxi_Surface(ic-1) + sxi_nxr / (2.d0 * Nx);
!     GWallSX(ic) = GWallSX(Nx_head) + xx_flateplate(ic + 1 - Nx_head) * cos(theta_p_rad);
!     GWallSY(ic) = GWallSY(Nx_head) + xx_flateplate(ic + 1 - Nx_head) * sin(theta_p_rad);
!     GWallNormalX(ic) = -sin(theta_p_rad);
!     GWallNormalY(ic) =  cos(theta_p_rad);
!    enddo
!
!  endif
!
!  ! define the Shock angle
!  call Calculate_ShockTheta(beta,theta_p_rad,Mach_Normal,Gamma)
!  
!  tan2 = tan(beta) * tan(beta);
!  ! 
!if( theta_p_deg >= 0.5_rk) then
!   ! the flate part is not horizontal
!   do ic = 1,Nx
!       
!           call Calculate_ShockHeight(GShockH(ic),&
!           GWallSX(ic), GWallSY(ic), GWallNormalX(ic), GWallNormalY(ic),delta, Rc, tan2)
!           
!   enddo
!else
!   
!    !If (Geometry_Type == 1)then
!    !   ic = 1
!    !  temp = R_head*R_head*tan2 &
!    !       + 2.d0 * R_head * delta * tan2 &
!    !       + delta * delta * tan2 &
!    !       + 2.d0 * R_head * Rc &
!    !       + 2.d0 * Rc * delta;
!    !shk_xgrid2  =  R_head;  
!    !shk_ygrid2  = -sqrt(temp);
!    !GShockH(ic) = sqrt((shk_xgrid2 - GWallSX(ic))**2.d0+(shk_ygrid2 - GWallSY(ic))**2.d0);
!             
!   do ic = 1,Nx_head
!     call Calculate_ShockHeight(GShockH(ic),&
!       GWallSX(ic), GWallSY(ic), GWallNormalX(ic), GWallNormalY(ic),delta, Rc, tan2)     
!   enddo
!  
!  
!   do ic = Nx_head+1,Nx
!     temp = GWallSX(ic)*GWallSX(ic)*tan2  &  
!          + 2.d0 * GWallSX(ic) * delta * tan2  & 
!          + delta * delta * tan2   &
!          + 2.d0 * GWallSX(ic) * Rc  &
!          + 2.d0 * Rc * delta;
!     shk_ygrid2 =  sqrt(temp);
!     shk_xgrid2 =  GWallSX(ic);
!    GShockH(ic) = sqrt((shk_xgrid2 - GWallSX(ic))**2.d0+(shk_ygrid2 - GWallSY(ic))**2.d0); 
!   enddo
!   
!  endif 
!
!  
!  ! Setting the grid points along I,K direction
!  do kc = 1,nz_local
!   kc_global = K_offset(npz) + kc - 1
!
!   do ic = 1,nx_local
!         ic_global = I_offset(npx) + ic - 1
!         WallSX(ic,kc) = GWallSX(ic_global);                           ! Surface X grid
!         WallSY(ic,kc) = GWallSY(ic_global)*cos(phi(kc_global));       ! Surface Y grid
!         WallSZ(ic,kc) = GWallSY(ic_global)*sin(phi(kc_global))*aspect_ratio ;  ! Surface Z grid
!     if (ic_global <= Nx_head) then
!         !norm_x = 1.d0
!         !norm_y = -WallSY(ic,kc)/R_head
!         !!norm_z = -WallSZ(ic,kc)*aspect_ratio/R_head
!         !norm_z = -WallSZ(ic,kc)*aspect_ratio**2/R_head
!         
!         norm_x = -(2.0_rk * (WallSX(ic,kc) - R_head) / (R_head * R_head))
!         norm_y = -2.0_rk * WallSY(ic,kc) / (R_head * R_head)
!         norm_z = -2.0_rk * WallSZ(ic,kc) / (R_head * R_head * aspect_ratio * aspect_ratio)
!     else
!       norm_x = sin(theta_p_rad)
!       norm_y = -cos(theta_p_rad)
!       norm_z = 0.0_rk
!       
!       ! 考虑周向角度φ的影响
!       ! 将法向量从局部坐标系转换到全局坐标系
!       temp_y = norm_y * cos(phi(kc_global)) - norm_z * sin(phi(kc_global))
!       temp_z = norm_y * sin(phi(kc_global)) + norm_z * cos(phi(kc_global))
!       norm_y = temp_y
!       norm_z = temp_z
!       
!       ! 考虑z方向的拉伸效应
!       norm_z = norm_z / aspect_ratio
!     endif         
!         norm_val = sqrt(norm_x**2 + norm_y**2 + norm_z**2)
!         WallNormalX(ic,kc) = -norm_x/norm_val
!         WallNormalY(ic,kc) = -norm_y/norm_val
!         WallNormalZ(ic,kc) = -norm_z/norm_val
!              
!    ShockH(ic,: ) = GShockH(ic_global)!*sqrt(cos(phi(kc_global))**2+sin(phi(kc_global))**2/aspect_ratio/aspect_ratio);            ! Shock Height
!    Sxi_Surface(ic,: ) = GSxi_Surface(ic_global);       ! Sxi surface
!   ENDDO
!
!  ENDDO
!  
!  
!  CALL Parallel_Exchange_singularity_surface(WallSX,WallSX_total)
!  CALL Parallel_Exchange_singularity_surface(WallSY,WallSY_total)
!  CALL Parallel_Exchange_singularity_surface(WallSZ,WallSZ_total)
!  CALL Parallel_Exchange_singularity_surface(WallNormalX,WallNormalX_total)
!  CALL Parallel_Exchange_singularity_surface(WallNormalY,WallNormalY_total)
!  CALL Parallel_Exchange_singularity_surface(WallNormalZ,WallNormalZ_total)
!  CALL Parallel_Exchange_singularity_surface(ShockH,shockH_total)
!  CALL Parallel_Exchange_singularity_surface(Sxi_Surface,Sxi_Surface_total)
!  
!
!  
!  Call Parallel_Exchange_Surface(WallSX)
!  Call Parallel_Exchange_Surface(WallSY)
!  Call Parallel_Exchange_Surface(WallSZ)
!  Call Parallel_Exchange_Surface(WallNormalX)
!  Call Parallel_Exchange_Surface(WallNormalY)
!  Call Parallel_Exchange_Surface(WallNormalZ)
!  Call Parallel_Exchange_Surface(ShockH)
!  Call Parallel_Exchange_Surface(Sxi_Surface) 
!  
!  ! The initial shock velocity is set to zero
!  ShockV = 0.0_rk;
!
!  ! generate the grid points on local domain for X , Y and Z directions 3D
!  DO kc = 1-overLAP,nz_local+overLAP
!   DO jc = 1,Ny
!    DO ic = 1-overLAP,nx_local+overLAP
!      X_grid(ic,jc,kc) = WallSX(ic,kc) + WallNormalX(ic,kc) * ShockH(ic,kc) * Heta(ic,jc,kc);
!      Y_grid(ic,jc,kc) = WallSY(ic,kc) + WallNormalY(ic,kc) * ShockH(ic,kc) * Heta(ic,jc,kc);
!      Z_grid(ic,jc,kc) = WallSZ(ic,kc) + WallNormalZ(ic,kc) * ShockH(ic,kc) * Heta(ic,jc,kc);
!    ENDDO
!   ENDDO
!  ENDDO
!  
!  call Parallel_Exchange_singularity(X_grid,X_grid_total)
!  call Parallel_Exchange_singularity(Y_grid,Y_grid_total)
!  call Parallel_Exchange_singularity(Z_grid,Z_grid_total)
!  
!  call Parallel_Exchange(X_grid)
!  call Parallel_Exchange(Y_grid)
!  call Parallel_Exchange(Z_grid)
!  
!  if(MyId == 0) then
!   write(*,*)"Output the initial grid" 
!  endif
!
!  call output_initial_grid
!
!  if(MyId == 0) then
!   write(*,*)"Output the initial grid finished" 
!  endif
!
!  ! Here we need to calculate some derivatives 
!  ! with respect to the Wall Surface variables
!   
!  ! only the xi direction need parallel exchange
!  
!   CALL Cal_Deri_SurfDxi_5th_ce(WallSXdxi,WallSX)
!   CALL Cal_Deri_SurfDxi_5th_ce(WallSYdxi,WallSY)
!   CALL Cal_Deri_SurfDxi_5th_ce(WallSZdxi,WallSZ)
!   CALL Cal_Deri_SurfDzeta_5th_ce(WallSXdzeta,WallSX)
!   CALL Cal_Deri_SurfDzeta_5th_ce(WallSYdzeta,WallSY)
!   CALL Cal_Deri_SurfDzeta_5th_ce(WallSZdzeta,WallSZ)
!   
!   call Parallel_Exchange_singularity_surface_negative(WallSXdxi,WallSXdxi_total)
!   call Parallel_Exchange_singularity_surface_negative(WallSYdxi,WallSYdxi_total)
!   call Parallel_Exchange_singularity_surface_negative(WallSZdxi,WallSZdxi_total)
!   call Parallel_Exchange_singularity_surface(WallSXdzeta,WallSXdzeta_total)
!   call Parallel_Exchange_singularity_surface(WallSYdzeta,WallSYdzeta_total)
!   call Parallel_Exchange_singularity_surface(WallSZdzeta,WallSZdzeta_total)
!   
!   
!   CALL Parallel_Exchange_Surface(WallSXdxi)
!   CALL Parallel_Exchange_Surface(WallSYdxi)
!   CALL Parallel_Exchange_Surface(WallSZdxi)
!   CALL Parallel_Exchange_Surface(WallSXdzeta)
!   CALL Parallel_Exchange_Surface(WallSYdzeta)
!   CALL Parallel_Exchange_Surface(WallSZdzeta)  
!   
!   
!   CALL Cal_Deri_SurfDxi_5th_ce(WallNormalXdxi,WallNormalX)
!   CALL Cal_Deri_SurfDxi_5th_ce(WallNormalYdxi,WallNormalY)
!   CALL Cal_Deri_SurfDxi_5th_ce(WallNormalZdxi,WallNormalZ)
!   CALL Cal_Deri_SurfDzeta_5th_ce(WallNormalXdzeta,WallNormalX)
!   CALL Cal_Deri_SurfDzeta_5th_ce(WallNormalYdzeta,WallNormalY)
!   CALL Cal_Deri_SurfDzeta_5th_ce(WallNormalZdzeta,WallNormalZ)  
!    
!   CALL Parallel_Exchange_singularity_surface_negative(WallNormalXdxi,WallNormalXdxi_total)
!   CALL Parallel_Exchange_singularity_surface_negative(WallNormalYdxi,WallNormalYdxi_total)
!   CALL Parallel_Exchange_singularity_surface_negative(WallNormalZdxi,WallNormalZdxi_total)
!   CALL Parallel_Exchange_singularity_surface(WallNormalXdzeta,WallNormalXdzeta_total)
!   CALL Parallel_Exchange_singularity_surface(WallNormalYdzeta,WallNormalYdzeta_total)
!   CALL Parallel_Exchange_singularity_surface(WallNormalZdzeta,WallNormalZdzeta_total)
!   
!   
!   CALL Parallel_Exchange_Surface(WallNormalXdxi)
!   CALL Parallel_Exchange_Surface(WallNormalYdxi)
!   CALL Parallel_Exchange_Surface(WallNormalZdxi)
!   CALL Parallel_Exchange_Surface(WallNormalXdzeta)
!   CALL Parallel_Exchange_Surface(WallNormalYdzeta)
!   CALL Parallel_Exchange_Surface(WallNormalZdzeta)
!
!   
!   !CALL Parallel_Exchange_singularity(Heta)   
!   CALL Parallel_Exchange(Heta)   
!   
!   CALL Cal_Deri_Dxi_5th_ce(HetaDxi,Heta)
!   CALL Cal_Deri_Deta_5th_ce(Hetadeta,Heta) 
!   CALL Cal_Deri_Dzeta_5th_ce_per(HetaDzeta,Heta)
!    
!   CALL Parallel_Exchange_singularity(HetaDxi,HetaDxi_total)
!   CALL Parallel_Exchange_singularity(Hetadeta,HetaDeta_total)
!   CALL Parallel_Exchange_singularity(HetaDzeta,HetaDzeta_total)
!   
!   CALL Parallel_Exchange(HetaDxi)
!   CALL Parallel_Exchange(Hetadeta)
!   CALL Parallel_Exchange(HetaDzeta) 
!  
!end subroutine Elliptical_Initial_Grid
!  
    
subroutine Hifire5b_Initial_Grid
  use SF_Constant,  only: ik,rk,pi,overLAP
  use SF_CFD_Global,only: Nx,nx_local,Ny,Nz,nz_local,Gamma,Geometry_Type,&
                          xim,ximax,sigma_y,yim,ymax,R_head,LModel,Nx_head,theta_p_rad,&
                          Mach_Normal,Nx_flate,Nx_head_hf,theta_p_deg
  use MPI_GLOBAL,   only: MyId,I_offset,K_offset,npx,npz
  ! arrays and matrixes
  use SF_CFD_Global,only: Heta,WallSX,WallSY,WallSZ,WallNormalX,WallNormalY,WallNormalZ,Sxi_Surface
  use SF_CFD_Global,only: HetaDeta,HetaDxi,HetaDzeta
  use SF_CFD_Global,only: WallSXdxi,WallSYdxi,WallSZdxi
  use SF_CFD_Global,only: WallSXdzeta,WallSYdzeta,WallSZdzeta
  use SF_CFD_Global,only: WallNormalXdxi,WallNormalYdxi,WallNormalZdxi
  use SF_CFD_Global,only: WallNormalXdzeta,WallNormalYdzeta,WallNormalZdzeta
  use SF_CFD_Global,only: ShockH,ShockV,X_grid,Y_grid,Z_grid,Lz_start,Lz_end
  use SF_CFD_Global,only: WallSX_total,WallSY_total,WallSZ_total,WallNormalX_total,WallNormalY_total,WallNormalZ_total,&
      &shockH_total,shockV_total,X_grid_total,Y_grid_total,Z_grid_total,WallSXdxi_total,WallSYdxi_total,WallSZdxi_total,&
      &WallSXdzeta_total,WallSYdzeta_total,WallSZdzeta_total,WallNormalXdxi_total,WallNormalYdxi_total,WallNormalZdxi_total,&
      &WallNormalXdzeta_total,WallNormalYdzeta_total,WallNormalZdzeta_total,Hetadxi_total,Hetadeta_total,Hetadzeta_total,Sxi_Surface_total
  ! subroutines
  use MPI_GLOBAL,     only: Parallel_Exchange,Parallel_Exchange_Surface
  use OutputParaView, only: output_initial_grid
  use FD5_Order,      only: Cal_Deri_SurfDxi_5th_ce,Cal_Deri_Deta_5th_ce,&
                           &Cal_Deri_Dxi_5th_ce,Cal_Deri_SurfDzeta_5th_ce,Cal_Deri_Dzeta_5th_ce_per!,Cal_Deri_Dzeta_5th_ce
    implicit none

    ! Local variables
           logical :: dir_exists
  INTEGER( kind=ik)::ic,jc,kc,ic_global,kc_global
  
  REAL( kind = rk )::S_head,S_flate,S_total
  REAL( kind = rk )::sxi_nxr
  ! Define some emperical Shock shape variables
  REAL( kind = rk )::delta, Rc, tan2,dxi
  ! Cluster coefficients along eta direction
  REAL( kind = rk )::eta_ay,eta_by,Ytemp,eta
  ! Coefficients along xi directions
  REAL( kind = rk )::szeta(1:Nz)
  REAL( kind = rk )::phi(1:Nz)
  REAL( kind = rk )::xi_ax,xi_bx,xi
  REAL( kind = rk )::sxi(1:2*Nx_head)
  REAL( kind = rk )::sxi0(1:Nx_head+1)
  REAL( kind = rk )::sxi_total(1:Nx_head)
  REAL( kind = rk )::theta_lcl
  REAL( kind = rk )::ds1,ds_uni,ds2
  
  REAL( kind = rk )::beta
  REAL( kind = rk )::GWallSX(1:Nx)
  REAL( kind = rk )::GWallSY(1:Nx)
  REAL( kind = rk )::GWallSZ(1:Nz)
  REAL( kind = rk )::GWallNormalX(1:Nx)
  REAL( kind = rk )::GWallNormalY(1:Nx)
  REAL( kind = rk )::GShockH(1:Nx)
  REAL( kind = rk )::GSxi_Surface(1:Nx)
  REAL( kind = rk )::shk_xgrid2,shk_ygrid2,temp
  REAL( kind = rk )::xx_flateplate(1:Nx_flate)
  character(len=8)  :: date 
  character(len=10) :: time
  real( kind = rk ), parameter :: a = 1.0d-3   ! 首项非零最小值（可调整，建议1e-3~1e-2）
  real( kind = rk ), parameter :: beta0 = 4.d0  ! 曲率控制参数（可调整，建议2.0~8.0）
  real( kind = rk ) :: scaled_xi, exp_term 
  real( kind = rk ), parameter :: aspect_ratio = 2.d0
  real( kind = rk ) :: norm_x,norm_y,norm_z,norm_val,temp_y,temp_z
  real( kind = rk ) ::  cos_phi,sin_phi,R_phi,R_circular,curvature_ratio,shock_height_factor
  ! Here we briefly describe the grid generation method
  ! This solver is used only for the grid in the x-y plane
  ! Then the grid in the z direction is generated by the duplication of the x-y plane
  ! The grid is generated by the following steps

  ! The geometry is defined by two parts, they first part is the rounded head part
  ! The second part is the flat plate part
  ! The grid is generated to have a blunt cone shape

  ! Define the streamwise sxi
  sxi          =  0.0_rk;
  sxi_total    =  0.0_rk;
  
  ! Global Wall Surface Coordinates (X,Y,Z)
  GWallSX      =  0.0_rk;
  GWallSY      =  0.0_rk;
  
  ! Global Wall Normal Vector (nwx,nwy,nwz)
  GWallNormalX =  0.0_rk;
  GWallNormalY =  0.0_rk;
  
  ! Global Shock-Wall Distance GShockH
  GShockH      =  0.0_rk;
  
  
  S_head     = R_head * (pi - 2.0_rk * theta_p_rad)/2.d0;
  
  S_flate    = (LModel - R_head*(1.0_rk - sin(theta_p_rad)))/cos(theta_p_rad);
  
  if(LModel <= R_head*(1.0_rk - sin(theta_p_rad))) then
    !write(*,*)"The model is too small, please check the input parameters"
    S_flate = 0.0_rk;
  endif

  S_total    = S_head + S_flate;

  sxi_nxr    = 0.5_rk * pi - theta_p_rad;  ! define the half head for the model

  ! For this wedge, we have
  !delta      = R_head * 0.386 * exp(4.67 / Mach_Normal / Mach_Normal);
  !  Rc       = R_head * 1.386 * exp(1.8/(Mach_Normal - 1.0)**0.75);  
  
  ! For this cone, we have
   delta      = R_head * 0.143 * exp(3.24 / Mach_Normal / Mach_Normal);
     Rc       = R_head * 1.143 * exp(0.54/(Mach_Normal - 1.0)**1.2);  
  
  ! define the Heta grid
   eta_ay    = ymax * yim / (ymax - 2.d0 * yim);
   eta_by    = 1.d0 + 2.d0 * eta_ay / ymax;

   DO jc = 1,Ny
        eta = -1.d0 + 2.d0 * (jc - 1.d0)/(Ny - 1.d0);   
      Ytemp = 2.d0 * ( (1.d0 - tanh(sigma_y)) * (eta + 1.d0)/2.d0)/&
                     ( 1.d0 - tanh( sigma_y * (eta + 1.d0)/2.d0) ) - 1.d0;
    Heta(:,jc,:)= eta_ay * (1.d0 + Ytemp)/(eta_by - Ytemp);
   ENDDO
  !
  ! define the xi grid
   
  dxi    = 2.d0/REAL(2*Nx_head - 1.d0);
  DO ic = 1,2*Nx_head
    sxi(ic) = -1.d0 + ( ic - 1.d0 )* dxi
  ENDDO
    sxi_total = sxi(Nx_head+1:2*Nx_head)
   
  !xi_ax      = ximax * xim / (ximax - 2.d0 * xim);
  !xi_bx      = 1.d0 + 2.d0 * xi_ax / ximax;
  !DO ic = 1,Nx_head
  !  xi = -1.d0 + 2.d0 * (ic - 1.d0)/(Nx_head - 1.d0);
  !  !sxi(ic) = (xi + 1.d0) / 2.d0;
  !  sxi(ic) = xi_ax * ( 1.d0 + xi )/( xi_bx - xi );
  !ENDDO
  !  sxi_total = sxi(1:Nx_head)
  !  sxi_total(1) = sxi_total(2)/4.d0
   
  !write(*,*)sxi_total
! define the szeta grid
  DO kc = 1,Nz
    szeta(kc) = (kc - 1.d0)/(Nz - 0.d0 );
      phi(kc) =  szeta(kc) * 2 * pi;
  enddo
  
  !% the first part
  !==============================================================================|
  !                                                                              |
  !                      Blunt Round 2D                                          |
  !                                                                              |
  !==============================================================================|
  
  DO ic = 1,Nx_head
    theta_lcl = sxi_total(ic) * sxi_nxr; 
    GSxi_Surface(ic) = theta_lcl;
    GWallSX(ic) = R_head * (1.d0 - cos(theta_lcl));
    GWallSY(ic) = R_head * sin(theta_lcl);
    GWallNormalX(ic) = -cos(theta_lcl);
    GWallNormalY(ic) =  sin(theta_lcl);
  ENDDO 
!!===========================================================================================|
!!                                                                                           |
!!                  Blunt Parabola 2D  （x = 1/(2*R) * y^2）                                 |
!!                                                                                           |
!!==========================================================================================!|
  
  !DO ic = 1,Nx_head
  !  theta_lcl = sxi_total(ic) * sxi_nxr; 
  !  GSxi_Surface(ic) = theta_lcl;
  !  
  !  GWallSY(ic) = sxi_total(ic) * 2 * R_head; 
  !  GWallSX(ic) = 1.d0/(2 * R_head) * (GWallSY(ic))**2;
  !  
  !  GWallNormalX(ic) = -1.d0 / sqrt((GWallSY(ic)/R_head)**2+1.d0);
  !  GWallNormalY(ic) = GWallSY(ic)/R_head/sqrt((GWallSY(ic)/R_head)**2+1.d0);
  !  
  !ENDDO
  
  if( S_flate > 0.d0 ) then
    ! start ds1
    ds1 = R_head * (sxi_total(Nx_head) * sxi_nxr - sxi_total(Nx_head-1) * sxi_nxr);
   
    ds_uni = S_flate / (Nx_flate - 1.d0);
  
    ds2 = max(3*ds1,3*ds_uni);
  
    call SettingTransformation(xx_flateplate,S_flate,Nx_flate,ds1,ds2)
    
    ! the second part
  
    Do ic = Nx_head+1,Nx
     GSxi_Surface(ic) = GSxi_Surface(ic-1) + sxi_nxr / (2.d0 * Nx);
     GWallSX(ic) = GWallSX(Nx_head) + xx_flateplate(ic + 1 - Nx_head) * cos(theta_p_rad);
     GWallSY(ic) = GWallSY(Nx_head) + xx_flateplate(ic + 1 - Nx_head) * sin(theta_p_rad);
     GWallNormalX(ic) = -sin(theta_p_rad);
     GWallNormalY(ic) =  cos(theta_p_rad);
    enddo

  endif

  ! define the Shock angle
   call Calculate_ShockTheta(beta,theta_p_rad,Mach_Normal,Gamma)
  tan2 = tan(beta) * tan(beta)
 
  if( theta_p_deg >= 0.5_rk) then 
    do ic = 1,Nx
      call Calculate_ShockHeight(GShockH(ic),&
              GWallSX(ic), GWallSY(ic), GWallNormalX(ic), GWallNormalY(ic),delta, Rc, tan2)
    enddo 
    
    ! do ic = Nx_head+1,Nx
    !  temp = GWallSX(ic)*GWallSX(ic)*tan2  &
    !         + 2.d0 * GWallSX(ic) * delta * tan2  &
    !         + delta * delta * tan2   &
    !         + 2.d0 * GWallSX(ic) * Rc  &
    !         + 2.d0 * Rc * delta
    !  shk_ygrid2 =  sqrt(temp)
    !  shk_xgrid2 =  GWallSX(ic)
    !  GShockH(ic) = sqrt((shk_xgrid2 - GWallSX(ic))**2.d0+(shk_ygrid2 - GWallSY(ic))**2.d0)
    !enddo
    
    
  else
    do ic = 1,Nx_head
      call Calculate_ShockHeight(GShockH(ic),&
        GWallSX(ic), GWallSY(ic), GWallNormalX(ic), GWallNormalY(ic),delta, Rc, tan2)
    enddo
    do ic = Nx_head+1,Nx
      temp = GWallSX(ic)*GWallSX(ic)*tan2  &
             + 2.d0 * GWallSX(ic) * delta * tan2  &
             + delta * delta * tan2   &
             + 2.d0 * GWallSX(ic) * Rc  &
             + 2.d0 * Rc * delta
      shk_ygrid2 =  sqrt(temp)
      shk_xgrid2 =  GWallSX(ic)
      GShockH(ic) = sqrt((shk_xgrid2 - GWallSX(ic))**2.d0+(shk_ygrid2 - GWallSY(ic))**2.d0)
    enddo
  endif 

  
  ! Setting the grid points along I,K direction
   do kc = 1,nz_local 
    kc_global = K_offset(npz) + kc - 1 
    do ic = 1,nx_local
      ic_global = I_offset(npx) + ic - 1
      
      ! 表面坐标 
      WallSX(ic,kc) = GWallSX(ic_global)
      WallSY(ic,kc) = GWallSY(ic_global)*cos(phi(kc_global))
      WallSZ(ic,kc) = GWallSY(ic_global)*sin(phi(kc_global))*aspect_ratio
 
      ! 法向量计算 
      if (ic_global <= Nx_head) then
        norm_x = -(2.0_rk * (WallSX(ic,kc) - R_head) / (R_head * R_head))
        norm_y = -2.0_rk * WallSY(ic,kc) / (R_head * R_head)
        norm_z = -2.0_rk * WallSZ(ic,kc) / (R_head * R_head * aspect_ratio * aspect_ratio)
      else 
        norm_x = sin(theta_p_rad)
        norm_y = -cos(theta_p_rad)
        norm_z = 0.0_rk 
        temp_y = norm_y * cos(phi(kc_global)) - norm_z * sin(phi(kc_global))
        temp_z = norm_y * sin(phi(kc_global)) + norm_z * cos(phi(kc_global))
        norm_y = temp_y
        norm_z = temp_z / aspect_ratio  ! 轴向缩放修正
      endif 
      
      ! 法向量归一化
      norm_val = sqrt(norm_x**2 + norm_y**2 + norm_z**2)
      WallNormalX(ic,kc) = -norm_x/norm_val
      WallNormalY(ic,kc) = -norm_y/norm_val 
      WallNormalZ(ic,kc) = -norm_z/norm_val
 
      ! ************************************************ 
      ! 关键修正：激波高度周向调整
      ! 引入椭圆截面修正因子，使激波形状与几何匹配 
      ! ************************************************
      !cos_phi = cos(phi(kc_global))
      !sin_phi = sin(phi(kc_global))
      !shock_height_factor = sqrt(cos_phi**2 + (aspect_ratio * sin_phi)**2)
      ShockH(ic, kc) = GShockH(ic_global)! * shock_height_factor
      
      Sxi_Surface(ic, kc) = GSxi_Surface(ic_global)
    ENDDO
  ENDDO
 
  ! --- 后续通信和网格生成（保持不变） --- 
  CALL Parallel_Exchange_singularity_surface(WallSX,WallSX_total)
  ! ... [其他通信调用] ...
  ShockV = 0.0_rk
  
  ! 生成三维网格点 
  DO kc = 1-overLAP,nz_local+overLAP 
    DO jc = 1,Ny 
      DO ic = 1-overLAP,nx_local+overLAP
        X_grid(ic,jc,kc) = WallSX(ic,kc) + WallNormalX(ic,kc) * ShockH(ic,kc) * Heta(ic,jc,kc)
        Y_grid(ic,jc,kc) = WallSY(ic,kc) + WallNormalY(ic,kc) * ShockH(ic,kc) * Heta(ic,jc,kc)
        Z_grid(ic,jc,kc) = WallSZ(ic,kc) + WallNormalZ(ic,kc) * ShockH(ic,kc) * Heta(ic,jc,kc)
      ENDDO 
    ENDDO 
  ENDDO 
  
  
  CALL Parallel_Exchange_singularity_surface(WallSX,WallSX_total)
  CALL Parallel_Exchange_singularity_surface(WallSY,WallSY_total)
  CALL Parallel_Exchange_singularity_surface(WallSZ,WallSZ_total)
  CALL Parallel_Exchange_singularity_surface(WallNormalX,WallNormalX_total)
  CALL Parallel_Exchange_singularity_surface(WallNormalY,WallNormalY_total)
  CALL Parallel_Exchange_singularity_surface(WallNormalZ,WallNormalZ_total)
  CALL Parallel_Exchange_singularity_surface(ShockH,shockH_total)
  CALL Parallel_Exchange_singularity_surface(Sxi_Surface,Sxi_Surface_total)
  

  
  Call Parallel_Exchange_Surface(WallSX)
  Call Parallel_Exchange_Surface(WallSY)
  Call Parallel_Exchange_Surface(WallSZ)
  Call Parallel_Exchange_Surface(WallNormalX)
  Call Parallel_Exchange_Surface(WallNormalY)
  Call Parallel_Exchange_Surface(WallNormalZ)
  Call Parallel_Exchange_Surface(ShockH)
  Call Parallel_Exchange_Surface(Sxi_Surface) 
  
  ! The initial shock velocity is set to zero
  ShockV = 0.0_rk;

  ! generate the grid points on local domain for X , Y and Z directions 3D
  DO kc = 1-overLAP,nz_local+overLAP
   DO jc = 1,Ny
    DO ic = 1-overLAP,nx_local+overLAP
      X_grid(ic,jc,kc) = WallSX(ic,kc) + WallNormalX(ic,kc) * ShockH(ic,kc) * Heta(ic,jc,kc);
      Y_grid(ic,jc,kc) = WallSY(ic,kc) + WallNormalY(ic,kc) * ShockH(ic,kc) * Heta(ic,jc,kc);
      Z_grid(ic,jc,kc) = WallSZ(ic,kc) + WallNormalZ(ic,kc) * ShockH(ic,kc) * Heta(ic,jc,kc);
    ENDDO
   ENDDO
  ENDDO
  
  call Parallel_Exchange_singularity(X_grid,X_grid_total)
  call Parallel_Exchange_singularity(Y_grid,Y_grid_total)
  call Parallel_Exchange_singularity(Z_grid,Z_grid_total)
  
  call Parallel_Exchange(X_grid)
  call Parallel_Exchange(Y_grid)
  call Parallel_Exchange(Z_grid)
  
  if(MyId == 0) then
   write(*,*)"Output the initial grid" 
  endif

  call output_initial_grid

  if(MyId == 0) then
   write(*,*)"Output the initial grid finished" 
  endif

  ! Here we need to calculate some derivatives 
  ! with respect to the Wall Surface variables
   
  ! only the xi direction need parallel exchange
  
   CALL Cal_Deri_SurfDxi_5th_ce(WallSXdxi,WallSX)
   CALL Cal_Deri_SurfDxi_5th_ce(WallSYdxi,WallSY)
   CALL Cal_Deri_SurfDxi_5th_ce(WallSZdxi,WallSZ)
   CALL Cal_Deri_SurfDzeta_5th_ce(WallSXdzeta,WallSX)
   CALL Cal_Deri_SurfDzeta_5th_ce(WallSYdzeta,WallSY)
   CALL Cal_Deri_SurfDzeta_5th_ce(WallSZdzeta,WallSZ)
   
   call Parallel_Exchange_singularity_surface_negative(WallSXdxi,WallSXdxi_total)
   call Parallel_Exchange_singularity_surface_negative(WallSYdxi,WallSYdxi_total)
   call Parallel_Exchange_singularity_surface_negative(WallSZdxi,WallSZdxi_total)
   call Parallel_Exchange_singularity_surface(WallSXdzeta,WallSXdzeta_total)
   call Parallel_Exchange_singularity_surface(WallSYdzeta,WallSYdzeta_total)
   call Parallel_Exchange_singularity_surface(WallSZdzeta,WallSZdzeta_total)
   
   
   CALL Parallel_Exchange_Surface(WallSXdxi)
   CALL Parallel_Exchange_Surface(WallSYdxi)
   CALL Parallel_Exchange_Surface(WallSZdxi)
   CALL Parallel_Exchange_Surface(WallSXdzeta)
   CALL Parallel_Exchange_Surface(WallSYdzeta)
   CALL Parallel_Exchange_Surface(WallSZdzeta)  
   
   
   CALL Cal_Deri_SurfDxi_5th_ce(WallNormalXdxi,WallNormalX)
   CALL Cal_Deri_SurfDxi_5th_ce(WallNormalYdxi,WallNormalY)
   CALL Cal_Deri_SurfDxi_5th_ce(WallNormalZdxi,WallNormalZ)
   CALL Cal_Deri_SurfDzeta_5th_ce(WallNormalXdzeta,WallNormalX)
   CALL Cal_Deri_SurfDzeta_5th_ce(WallNormalYdzeta,WallNormalY)
   CALL Cal_Deri_SurfDzeta_5th_ce(WallNormalZdzeta,WallNormalZ)  
    
   CALL Parallel_Exchange_singularity_surface_negative(WallNormalXdxi,WallNormalXdxi_total)
   CALL Parallel_Exchange_singularity_surface_negative(WallNormalYdxi,WallNormalYdxi_total)
   CALL Parallel_Exchange_singularity_surface_negative(WallNormalZdxi,WallNormalZdxi_total)
   CALL Parallel_Exchange_singularity_surface(WallNormalXdzeta,WallNormalXdzeta_total)
   CALL Parallel_Exchange_singularity_surface(WallNormalYdzeta,WallNormalYdzeta_total)
   CALL Parallel_Exchange_singularity_surface(WallNormalZdzeta,WallNormalZdzeta_total)
   
   
   CALL Parallel_Exchange_Surface(WallNormalXdxi)
   CALL Parallel_Exchange_Surface(WallNormalYdxi)
   CALL Parallel_Exchange_Surface(WallNormalZdxi)
   CALL Parallel_Exchange_Surface(WallNormalXdzeta)
   CALL Parallel_Exchange_Surface(WallNormalYdzeta)
   CALL Parallel_Exchange_Surface(WallNormalZdzeta)

   
   !CALL Parallel_Exchange_singularity(Heta)   
   CALL Parallel_Exchange(Heta)   
   
   CALL Cal_Deri_Dxi_5th_ce(HetaDxi,Heta)
   CALL Cal_Deri_Deta_5th_ce(Hetadeta,Heta) 
   CALL Cal_Deri_Dzeta_5th_ce_per(HetaDzeta,Heta)
    
   CALL Parallel_Exchange_singularity(HetaDxi,HetaDxi_total)
   CALL Parallel_Exchange_singularity(Hetadeta,HetaDeta_total)
   CALL Parallel_Exchange_singularity(HetaDzeta,HetaDzeta_total)
   
   CALL Parallel_Exchange(HetaDxi)
   CALL Parallel_Exchange(Hetadeta)
   CALL Parallel_Exchange(HetaDzeta) 
  
end subroutine Hifire5b_Initial_Grid  
    
subroutine Elliptical_Initial_Grid
  use SF_Constant,  only: ik,rk,pi,overLAP
  use SF_CFD_Global,only: Nx,nx_local,Ny,Nz,nz_local,Gamma,Geometry_Type,&
                          xim,ximax,sigma_y,yim,ymax,R_head,LModel,Nx_head,theta_p_rad,&
                          Mach_Normal,Nx_flate,Nx_head_hf,theta_p_deg
  use MPI_GLOBAL,   only: MyId,I_offset,K_offset,npx,npz
  ! arrays and matrixes
  use SF_CFD_Global,only: Heta,WallSX,WallSY,WallSZ,WallNormalX,WallNormalY,WallNormalZ,Sxi_Surface
  use SF_CFD_Global,only: HetaDeta,HetaDxi,HetaDzeta
  use SF_CFD_Global,only: WallSXdxi,WallSYdxi,WallSZdxi
  use SF_CFD_Global,only: WallSXdzeta,WallSYdzeta,WallSZdzeta
  use SF_CFD_Global,only: WallNormalXdxi,WallNormalYdxi,WallNormalZdxi
  use SF_CFD_Global,only: WallNormalXdzeta,WallNormalYdzeta,WallNormalZdzeta
  use SF_CFD_Global,only: ShockH,ShockV,X_grid,Y_grid,Z_grid,Lz_start,Lz_end
  use SF_CFD_Global,only: WallSX_total,WallSY_total,WallSZ_total,WallNormalX_total,WallNormalY_total,WallNormalZ_total,&
      &shockH_total,shockV_total,X_grid_total,Y_grid_total,Z_grid_total,WallSXdxi_total,WallSYdxi_total,WallSZdxi_total,&
      &WallSXdzeta_total,WallSYdzeta_total,WallSZdzeta_total,WallNormalXdxi_total,WallNormalYdxi_total,WallNormalZdxi_total,&
      &WallNormalXdzeta_total,WallNormalYdzeta_total,WallNormalZdzeta_total,Hetadxi_total,Hetadeta_total,Hetadzeta_total,Sxi_Surface_total
  ! subroutines
  use MPI_GLOBAL,     only: Parallel_Exchange,Parallel_Exchange_Surface
  use OutputParaView, only: output_initial_grid
  use FD5_Order,      only: Cal_Deri_SurfDxi_5th_ce,Cal_Deri_Deta_5th_ce,&
                           &Cal_Deri_Dxi_5th_ce,Cal_Deri_SurfDzeta_5th_ce,Cal_Deri_Dzeta_5th_ce_per!,Cal_Deri_Dzeta_5th_ce
    implicit none

    ! Local variables
           logical :: dir_exists
  INTEGER( kind=ik)::ic,jc,kc,ic_global,kc_global
  
  REAL( kind = rk )::S_head,S_flate,S_total
  REAL( kind = rk )::sxi_nxr
  ! Define some emperical Shock shape variables
  REAL( kind = rk )::delta, Rc, tan2,dxi
  ! Cluster coefficients along eta direction
  REAL( kind = rk )::eta_ay,eta_by,Ytemp,eta
  ! Coefficients along xi directions
  REAL( kind = rk )::szeta(1:Nz)
  REAL( kind = rk )::phi(1:Nz)
  REAL( kind = rk )::xi_ax,xi_bx,xi
  REAL( kind = rk )::sxi(1:2*Nx_head)
  REAL( kind = rk )::sxi0(1:Nx_head+1)
  REAL( kind = rk )::sxi_total(1:Nx_head)
  REAL( kind = rk )::theta_lcl
  REAL( kind = rk )::ds1,ds_uni,ds2
  
  REAL( kind = rk )::beta
  REAL( kind = rk )::GWallSX(1:Nx)
  REAL( kind = rk )::GWallSY(1:Nx)
  REAL( kind = rk )::GWallSZ(1:Nz)
  REAL( kind = rk )::GWallNormalX(1:Nx)
  REAL( kind = rk )::GWallNormalY(1:Nx)
  REAL( kind = rk )::GShockH(1:Nx)
  REAL( kind = rk )::GSxi_Surface(1:Nx)
  REAL( kind = rk )::shk_xgrid2,shk_ygrid2,temp
  REAL( kind = rk )::xx_flateplate(1:Nx_flate)
  character(len=8)  :: date 
  character(len=10) :: time
  real( kind = rk ), parameter :: a = 1.0d-3   ! 首项非零最小值（可调整，建议1e-3~1e-2）
  real( kind = rk ), parameter :: beta0 = 4.d0  ! 曲率控制参数（可调整，建议2.0~8.0）
  real( kind = rk ) :: scaled_xi, exp_term 
  real( kind = rk ), parameter :: aspect_ratio = 2.d0
  real( kind = rk ) :: norm_x,norm_y,norm_z,norm_val
  ! Here we briefly describe the grid generation method
  ! This solver is used only for the grid in the x-y plane
  ! Then the grid in the z direction is generated by the duplication of the x-y plane
  ! The grid is generated by the following steps

  ! The geometry is defined by two parts, they first part is the rounded head part
  ! The second part is the flat plate part
  ! The grid is generated to have a blunt cone shape

  ! Define the streamwise sxi
  sxi          =  0.0_rk;
  sxi_total    =  0.0_rk;
  
  ! Global Wall Surface Coordinates (X,Y,Z)
  GWallSX      =  0.0_rk;
  GWallSY      =  0.0_rk;
  
  ! Global Wall Normal Vector (nwx,nwy,nwz)
  GWallNormalX =  0.0_rk;
  GWallNormalY =  0.0_rk;
  
  ! Global Shock-Wall Distance GShockH
  GShockH      =  0.0_rk;
  
  
  S_head     = R_head * (pi - 2.0_rk * theta_p_rad)/2.d0;
  
  S_flate    = (LModel - R_head*(1.0_rk - sin(theta_p_rad)))/cos(theta_p_rad);
  
  if(LModel <= R_head*(1.0_rk - sin(theta_p_rad))) then
    !write(*,*)"The model is too small, please check the input parameters"
    S_flate = 0.0_rk;
  endif

  S_total    = S_head + S_flate;

  sxi_nxr    = 0.5_rk * pi - theta_p_rad;  ! define the half head for the model

  ! For this wedge, we have
  !delta      = R_head * 0.386 * exp(4.67 / Mach_Normal / Mach_Normal);
  !  Rc       = R_head * 1.386 * exp(1.8/(Mach_Normal - 1.0)**0.75);  
  
  ! For this cone, we have
   delta      = R_head * 0.143 * exp(3.24 / Mach_Normal / Mach_Normal);
     Rc       = R_head * 1.143 * exp(0.54/(Mach_Normal - 1.0)**1.2);  
  
  ! define the Heta grid
   eta_ay    = ymax * yim / (ymax - 2.d0 * yim);
   eta_by    = 1.d0 + 2.d0 * eta_ay / ymax;

   DO jc = 1,Ny
        eta = -1.d0 + 2.d0 * (jc - 1.d0)/(Ny - 1.d0);   
      Ytemp = 2.d0 * ( (1.d0 - tanh(sigma_y)) * (eta + 1.d0)/2.d0)/&
                     ( 1.d0 - tanh( sigma_y * (eta + 1.d0)/2.d0) ) - 1.d0;
    Heta(:,jc,:)= eta_ay * (1.d0 + Ytemp)/(eta_by - Ytemp);
   ENDDO
  !
  ! define the xi grid
   
  dxi    = 2.d0/REAL(2*Nx_head - 1.d0);
  DO ic = 1,2*Nx_head
    sxi(ic) = -1.d0 + ( ic - 1.d0 )* dxi
  ENDDO
    sxi_total = sxi(Nx_head+1:2*Nx_head)
   
  !xi_ax      = ximax * xim / (ximax - 2.d0 * xim);
  !xi_bx      = 1.d0 + 2.d0 * xi_ax / ximax;
  !DO ic = 1,Nx_head
  !  xi = -1.d0 + 2.d0 * (ic - 1.d0)/(Nx_head - 1.d0);
  !  !sxi(ic) = (xi + 1.d0) / 2.d0;
  !  sxi(ic) = xi_ax * ( 1.d0 + xi )/( xi_bx - xi );
  !ENDDO
  !  sxi_total = sxi(1:Nx_head)
  !  sxi_total(1) = sxi_total(2)/4.d0
   
  !write(*,*)sxi_total
! define the szeta grid
  DO kc = 1,Nz
    szeta(kc) = (kc - 1.d0)/(Nz - 0.d0 );
      phi(kc) =  szeta(kc) * 2 * pi;
  enddo
  
  !% the first part
  !==============================================================================|
  !                                                                              |
  !                      Blunt Round 2D                                          |
  !                                                                              |
  !==============================================================================|
  
  !DO ic = 1,Nx_head
  !  theta_lcl = sxi_total(ic) * sxi_nxr; 
  !  GSxi_Surface(ic) = theta_lcl;
  !  GWallSX(ic) = R_head * (1.d0 - cos(theta_lcl));
  !  GWallSY(ic) = R_head * sin(theta_lcl);
  !  GWallNormalX(ic) = -cos(theta_lcl);
  !  GWallNormalY(ic) = sin(theta_lcl);
  !ENDDO 
!!===========================================================================================|
!!                                                                                           |
!!                  Blunt Parabola 2D  （x = 1/(2*R) * y^2）                                 |
!!                                                                                           |
!!==========================================================================================!|
  
  DO ic = 1,Nx_head
    theta_lcl = sxi_total(ic) * sxi_nxr; 
    GSxi_Surface(ic) = theta_lcl;
    
    GWallSY(ic) = sxi_total(ic) * 2 * R_head; 
    GWallSX(ic) = 1.d0/(2 * R_head) * (GWallSY(ic))**2;
    
    GWallNormalX(ic) = -1.d0 / sqrt((GWallSY(ic)/R_head)**2+1.d0);
    GWallNormalY(ic) = GWallSY(ic)/R_head/sqrt((GWallSY(ic)/R_head)**2+1.d0);
    
  ENDDO
  
  
  if( S_flate > 0.d0 ) then
    ! start ds1
    ds1 = R_head * (sxi_total(Nx_head) * sxi_nxr - sxi_total(Nx_head-1) * sxi_nxr);
   
    ds_uni = S_flate / (Nx_flate - 1.d0);
  
    ds2 = max(3*ds1,3*ds_uni);
  
    call SettingTransformation(xx_flateplate,S_flate,Nx_flate,ds1,ds2)
    
 !write(*,*)xx_flateplate  
    ! the second part
  
    Do ic = Nx_head+1,Nx
     GSxi_Surface(ic) = GSxi_Surface(ic-1) + sxi_nxr / (2.d0 * Nx);
     GWallSX(ic) = GWallSX(Nx_head) + xx_flateplate(ic + 1 - Nx_head) * cos(theta_p_rad);
     GWallSY(ic) = GWallSY(Nx_head) + xx_flateplate(ic + 1 - Nx_head) * sin(theta_p_rad);
     GWallNormalX(ic) = -sin(theta_p_rad);
     GWallNormalY(ic) =  cos(theta_p_rad);
    enddo

  endif

  ! define the Shock angle
  call Calculate_ShockTheta(beta,theta_p_rad,Mach_Normal,Gamma)
  
  tan2 = tan(beta) * tan(beta);
  ! 
if( theta_p_deg >= 0.5_rk) then
   ! the flate part is not horizontal
   do ic = 1,Nx
       !do kc = 1,Nz
         !if (kc < Nz/2 + 1) then
           call Calculate_ShockHeight(GShockH(ic),&
           GWallSX(ic), GWallSY(ic), GWallNormalX(ic), GWallNormalY(ic),delta, Rc, tan2)
         !else
         !  call Calculate_ShockHeight(GShockH(ic),&
         !  GWallSX(ic), -GWallSY(ic), GWallNormalX(ic), -GWallNormalY(ic),delta, Rc, tan2)      
         !endif
         
       !enddo
   enddo
else

   
    !If (Geometry_Type == 1)then
    !   ic = 1
    !  temp = R_head*R_head*tan2 &
    !       + 2.d0 * R_head * delta * tan2 &
    !       + delta * delta * tan2 &
    !       + 2.d0 * R_head * Rc &
    !       + 2.d0 * Rc * delta;
    !shk_xgrid2  =  R_head;  
    !shk_ygrid2  = -sqrt(temp);
    !GShockH(ic) = sqrt((shk_xgrid2 - GWallSX(ic))**2.d0+(shk_ygrid2 - GWallSY(ic))**2.d0);
             
   do ic = 1,Nx_head
     call Calculate_ShockHeight(GShockH(ic),&
       GWallSX(ic), GWallSY(ic), GWallNormalX(ic), GWallNormalY(ic),delta, Rc, tan2)     
   enddo
  
  
   do ic = Nx_head+1,Nx
     temp = GWallSX(ic)*GWallSX(ic)*tan2  &  
          + 2.d0 * GWallSX(ic) * delta * tan2  & 
          + delta * delta * tan2   &
          + 2.d0 * GWallSX(ic) * Rc  &
          + 2.d0 * Rc * delta;
     shk_ygrid2 =  sqrt(temp);
     shk_xgrid2 =  GWallSX(ic);
    GShockH(ic) = sqrt((shk_xgrid2 - GWallSX(ic))**2.d0+(shk_ygrid2 - GWallSY(ic))**2.d0); 
   enddo
   
  endif 

  
  ! Setting the grid points along I,K direction
  do kc = 1,nz_local
   kc_global = K_offset(npz) + kc - 1

   do ic = 1,nx_local
             ic_global = I_offset(npx) + ic - 1
         WallSX(ic,kc) = GWallSX(ic_global);                           ! Surface X grid
         WallSY(ic,kc) = GWallSY(ic_global)*cos(phi(kc_global));       ! Surface Y grid
         WallSZ(ic,kc) = GWallSY(ic_global)*sin(phi(kc_global))/aspect_ratio ;       ! Surface Z grid
    !WallNormalX(ic,kc) = GWallNormalX(ic_global);                      ! Surface wallnormal vector X
    !WallNormalY(ic,kc) = GWallNormalY(ic_global)*cos(phi(kc_global));  ! Surface wallnormal vector Y
    !WallNormalZ(ic,kc) = GWallNormalY(ic_global)*sin(phi(kc_global))*aspect_ratio ;  ! Surface wallnormal vector Z
         norm_x = 1.d0
         norm_y = -WallSY(ic,kc)/R_head
         norm_z = -WallSZ(ic,kc)*aspect_ratio**2/R_head
         norm_val = sqrt(norm_x**2 + norm_y**2 + norm_z**2)
         WallNormalX(ic,kc) = -norm_x/norm_val
         WallNormalY(ic,kc) = -norm_y/norm_val
         WallNormalZ(ic,kc) = -norm_z/norm_val

         ShockH(ic,: ) = GShockH(ic_global);                           ! Shock Height
    Sxi_Surface(ic,: ) = GSxi_Surface(ic_global);                      ! Sxi surface
   ENDDO

  ENDDO
  
  CALL Parallel_Exchange_singularity_surface(WallSX,WallSX_total)
  CALL Parallel_Exchange_singularity_surface(WallSY,WallSY_total)
  CALL Parallel_Exchange_singularity_surface(WallSZ,WallSZ_total)
  CALL Parallel_Exchange_singularity_surface(WallNormalX,WallNormalX_total)
  CALL Parallel_Exchange_singularity_surface(WallNormalY,WallNormalY_total)
  CALL Parallel_Exchange_singularity_surface(WallNormalZ,WallNormalZ_total)
  CALL Parallel_Exchange_singularity_surface(ShockH,shockH_total)
  CALL Parallel_Exchange_singularity_surface(Sxi_Surface,Sxi_Surface_total)
  

  
  Call Parallel_Exchange_Surface(WallSX)
  Call Parallel_Exchange_Surface(WallSY)
  Call Parallel_Exchange_Surface(WallSZ)
  Call Parallel_Exchange_Surface(WallNormalX)
  Call Parallel_Exchange_Surface(WallNormalY)
  Call Parallel_Exchange_Surface(WallNormalZ)
  Call Parallel_Exchange_Surface(ShockH)
  Call Parallel_Exchange_Surface(Sxi_Surface) 
  
  ! The initial shock velocity is set to zero
  ShockV = 0.0_rk;

  ! generate the grid points on local domain for X , Y and Z directions 3D
  DO kc = 1-overLAP,nz_local+overLAP
   DO jc = 1,Ny
    DO ic = 1-overLAP,nx_local+overLAP
      X_grid(ic,jc,kc) = WallSX(ic,kc) + WallNormalX(ic,kc) * ShockH(ic,kc) * Heta(ic,jc,kc);
      Y_grid(ic,jc,kc) = WallSY(ic,kc) + WallNormalY(ic,kc) * ShockH(ic,kc) * Heta(ic,jc,kc);
      Z_grid(ic,jc,kc) = WallSZ(ic,kc) + WallNormalZ(ic,kc) * ShockH(ic,kc) * Heta(ic,jc,kc);
    ENDDO
   ENDDO
  ENDDO
  
  call Parallel_Exchange_singularity(X_grid,X_grid_total)
  call Parallel_Exchange_singularity(Y_grid,Y_grid_total)
  call Parallel_Exchange_singularity(Z_grid,Z_grid_total)
  
  call Parallel_Exchange(X_grid)
  call Parallel_Exchange(Y_grid)
  call Parallel_Exchange(Z_grid)
  
  if(MyId == 0) then
   write(*,*)"Output the initial grid" 
  endif

  call output_initial_grid

  if(MyId == 0) then
   write(*,*)"Output the initial grid finished" 
  endif

  ! Here we need to calculate some derivatives 
  ! with respect to the Wall Surface variables
   
  ! only the xi direction need parallel exchange
  
   CALL Cal_Deri_SurfDxi_5th_ce(WallSXdxi,WallSX)
   CALL Cal_Deri_SurfDxi_5th_ce(WallSYdxi,WallSY)
   CALL Cal_Deri_SurfDxi_5th_ce(WallSZdxi,WallSZ)
   CALL Cal_Deri_SurfDzeta_5th_ce(WallSXdzeta,WallSX)
   CALL Cal_Deri_SurfDzeta_5th_ce(WallSYdzeta,WallSY)
   CALL Cal_Deri_SurfDzeta_5th_ce(WallSZdzeta,WallSZ)
   
   call Parallel_Exchange_singularity_surface_negative(WallSXdxi,WallSXdxi_total)
   call Parallel_Exchange_singularity_surface_negative(WallSYdxi,WallSYdxi_total)
   call Parallel_Exchange_singularity_surface_negative(WallSZdxi,WallSZdxi_total)
   call Parallel_Exchange_singularity_surface(WallSXdzeta,WallSXdzeta_total)
   call Parallel_Exchange_singularity_surface(WallSYdzeta,WallSYdzeta_total)
   call Parallel_Exchange_singularity_surface(WallSZdzeta,WallSZdzeta_total)
   
   
   CALL Parallel_Exchange_Surface(WallSXdxi)
   CALL Parallel_Exchange_Surface(WallSYdxi)
   CALL Parallel_Exchange_Surface(WallSZdxi)
   CALL Parallel_Exchange_Surface(WallSXdzeta)
   CALL Parallel_Exchange_Surface(WallSYdzeta)
   CALL Parallel_Exchange_Surface(WallSZdzeta)  
   
   
   CALL Cal_Deri_SurfDxi_5th_ce(WallNormalXdxi,WallNormalX)
   CALL Cal_Deri_SurfDxi_5th_ce(WallNormalYdxi,WallNormalY)
   CALL Cal_Deri_SurfDxi_5th_ce(WallNormalZdxi,WallNormalZ)
   CALL Cal_Deri_SurfDzeta_5th_ce(WallNormalXdzeta,WallNormalX)
   CALL Cal_Deri_SurfDzeta_5th_ce(WallNormalYdzeta,WallNormalY)
   CALL Cal_Deri_SurfDzeta_5th_ce(WallNormalZdzeta,WallNormalZ)  
    
   CALL Parallel_Exchange_singularity_surface_negative(WallNormalXdxi,WallNormalXdxi_total)
   CALL Parallel_Exchange_singularity_surface_negative(WallNormalYdxi,WallNormalYdxi_total)
   CALL Parallel_Exchange_singularity_surface_negative(WallNormalZdxi,WallNormalZdxi_total)
   CALL Parallel_Exchange_singularity_surface(WallNormalXdzeta,WallNormalXdzeta_total)
   CALL Parallel_Exchange_singularity_surface(WallNormalYdzeta,WallNormalYdzeta_total)
   CALL Parallel_Exchange_singularity_surface(WallNormalZdzeta,WallNormalZdzeta_total)
   
   
   CALL Parallel_Exchange_Surface(WallNormalXdxi)
   CALL Parallel_Exchange_Surface(WallNormalYdxi)
   CALL Parallel_Exchange_Surface(WallNormalZdxi)
   CALL Parallel_Exchange_Surface(WallNormalXdzeta)
   CALL Parallel_Exchange_Surface(WallNormalYdzeta)
   CALL Parallel_Exchange_Surface(WallNormalZdzeta)

   
   !CALL Parallel_Exchange_singularity(Heta)   
   CALL Parallel_Exchange(Heta)   
   
   CALL Cal_Deri_Dxi_5th_ce(HetaDxi,Heta)
   CALL Cal_Deri_Deta_5th_ce(Hetadeta,Heta) 
   CALL Cal_Deri_Dzeta_5th_ce_per(HetaDzeta,Heta)
    
   CALL Parallel_Exchange_singularity(HetaDxi,HetaDxi_total)
   CALL Parallel_Exchange_singularity(Hetadeta,HetaDeta_total)
   CALL Parallel_Exchange_singularity(HetaDzeta,HetaDzeta_total)
   
   CALL Parallel_Exchange(HetaDxi)
   CALL Parallel_Exchange(Hetadeta)
   CALL Parallel_Exchange(HetaDzeta) 
  
  end subroutine Elliptical_Initial_Grid    